// Comprehensive demo course data for fallback when database is unavailable
// This data represents actual Purdue ECE courses

export interface DemoCourse {
  id: string;
  code: string;
  name: string;
  credits: number;
  description: string;
  avgGPA: number;
  difficultyRating: number;
  workloadHours: number;
  reviewCount: number;
  prerequisites: string[];
  corequisites: string[];
  semesters: string[];
  careerTags: string[];
  interestTags: string[];
  level: number;
  professors: string[];
  typicalDays: string[];
  hasMorningSection: boolean;
  hasAfternoonSection: boolean;
  hasEveningSection: boolean;
  hasFridayClass: boolean;
  hasOnlineOption: boolean;
  hasHybridOption: boolean;
  numExams: number;
  isProjectBased: boolean;
  isExamBased: boolean;
  homeworkIntensity: string;
  isCodingHeavy: boolean;
  isMathHeavy: boolean;
  examIntensity: string;
  hasGroupProjects: boolean;
  isMajorRequirement: boolean;
  isTechElective: boolean;
  isGenEd: boolean;
  isLabCredit: boolean;
  requirementCategory: string;
  gradeDistribution: { A: number; B: number; C: number; D: number; F: number };
  reviews: Array<{
    id: string;
    rating: number;
    difficulty: number;
    workload: number;
    comment: string;
    professor: string;
    semester: string;
    source: string;
  }>;
}

export const DEMO_COURSES: DemoCourse[] = [
  // 20000-level courses (Sophomore)
  {
    id: 'c1', code: 'ECE 20001', name: 'Electrical Engineering Fundamentals I', credits: 3,
    description: 'Introduction to electrical engineering concepts including basic circuit elements, Kirchhoffs laws, nodal and mesh analysis, Thevenin and Norton equivalent circuits, and operational amplifiers.',
    avgGPA: 2.85, difficultyRating: 3.2, workloadHours: 12, reviewCount: 156,
    prerequisites: ['PHYS 17200', 'MA 26100'], corequisites: ['ECE 20007'],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['hardware', 'embedded', 'signals'],
    interestTags: ['circuits', 'physics', 'analog'], level: 20000,
    professors: ['Mark Johnson', 'Shreyas Sen'], typicalDays: ['MWF', 'TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 18, B: 28, C: 30, D: 14, F: 10 },
    reviews: [
      { id: 'r1', rating: 3, difficulty: 4, workload: 12, comment: 'Challenging but foundational. Make sure you understand KVL/KCL well.', professor: 'Mark Johnson', semester: 'Fall 2024', source: 'BoilerGrades' },
      { id: 'r2', rating: 4, difficulty: 3, workload: 10, comment: 'Dr. Sen explains concepts clearly. Office hours are helpful.', professor: 'Shreyas Sen', semester: 'Spring 2024', source: 'RateMyProfessor' },
    ]
  },
  {
    id: 'c2', code: 'ECE 20002', name: 'Electrical Engineering Fundamentals II', credits: 3,
    description: 'Continuation of ECE 20001. Second-order transient response, sinusoidal steady-state response, AC power analysis, frequency response, and introduction to filters.',
    avgGPA: 2.78, difficultyRating: 3.4, workloadHours: 13, reviewCount: 142,
    prerequisites: ['ECE 20001'], corequisites: ['ECE 20008'],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['hardware', 'signals', 'power'],
    interestTags: ['circuits', 'analog', 'physics'], level: 20000,
    professors: ['Mark Johnson', 'Byunghoo Jung'], typicalDays: ['MWF', 'TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 15, B: 26, C: 32, D: 16, F: 11 },
    reviews: [
      { id: 'r3', rating: 3, difficulty: 4, workload: 13, comment: 'Harder than 20001. Frequency response takes time to understand.', professor: 'Mark Johnson', semester: 'Spring 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c3', code: 'ECE 20007', name: 'Electrical Engineering Fundamentals Lab I', credits: 1,
    description: 'Laboratory experiments covering circuit analysis techniques, use of test equipment, and introduction to electronic components.',
    avgGPA: 3.45, difficultyRating: 2.2, workloadHours: 4, reviewCount: 98,
    prerequisites: [], corequisites: ['ECE 20001'],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['hardware', 'embedded'],
    interestTags: ['circuits', 'hands-on'], level: 20000,
    professors: ['Lab Staff'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: true,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'light',
    isCodingHeavy: false, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: true,
    requirementCategory: 'core',
    gradeDistribution: { A: 45, B: 35, C: 15, D: 3, F: 2 },
    reviews: []
  },
  {
    id: 'c4', code: 'ECE 20875', name: 'Python for Data Science', credits: 3,
    description: 'Introduction to Python programming with applications in data analysis, visualization, and basic machine learning. Covers NumPy, Pandas, Matplotlib, and scikit-learn.',
    avgGPA: 3.25, difficultyRating: 2.5, workloadHours: 10, reviewCount: 203,
    prerequisites: [], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['software', 'ml'],
    interestTags: ['programming', 'data', 'math'], level: 20000,
    professors: ['David Inouye', 'Stanley Chan'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: true,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'breadth',
    gradeDistribution: { A: 35, B: 32, C: 22, D: 7, F: 4 },
    reviews: [
      { id: 'r4', rating: 5, difficulty: 2, workload: 8, comment: 'Great intro to Python and data science. Very practical skills.', professor: 'David Inouye', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  // 26000-level courses
  {
    id: 'c5', code: 'ECE 26400', name: 'Advanced C Programming', credits: 3,
    description: 'Advanced C programming concepts including pointers, dynamic memory allocation, file I/O, data structures, and software engineering principles.',
    avgGPA: 2.92, difficultyRating: 3.5, workloadHours: 14, reviewCount: 178,
    prerequisites: ['CS 15900'], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['software', 'embedded'],
    interestTags: ['programming', 'systems'], level: 26000,
    professors: ['Yung-Hsiang Lu', 'Cheng-Kok Koh'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 22, B: 30, C: 28, D: 12, F: 8 },
    reviews: [
      { id: 'r5', rating: 4, difficulty: 4, workload: 14, comment: 'Challenging but essential for embedded systems. Start projects early.', professor: 'Yung-Hsiang Lu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  // 27000-level courses
  {
    id: 'c6', code: 'ECE 27000', name: 'Introduction to Digital System Design', credits: 4,
    description: 'Boolean algebra, combinational and sequential logic design, finite state machines, programmable logic devices, and hardware description languages (Verilog).',
    avgGPA: 2.95, difficultyRating: 3.3, workloadHours: 14, reviewCount: 165,
    prerequisites: [], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['hardware', 'embedded', 'vlsi'],
    interestTags: ['digital', 'circuits', 'fpga'], level: 27000,
    professors: ['Cheng-Kok Koh', 'Vijay Raghunathan'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: true,
    requirementCategory: 'core',
    gradeDistribution: { A: 24, B: 30, C: 26, D: 12, F: 8 },
    reviews: [
      { id: 'r6', rating: 4, difficulty: 3, workload: 14, comment: 'Fun course if you like hardware. Labs can be time-consuming.', professor: 'Cheng-Kok Koh', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  // 30000-level courses
  {
    id: 'c7', code: 'ECE 30100', name: 'Signals and Systems', credits: 3,
    description: 'Continuous and discrete-time signals and systems. Convolution, Fourier series, Fourier transform, Laplace transform, Z-transform, and system analysis.',
    avgGPA: 2.58, difficultyRating: 4.2, workloadHours: 15, reviewCount: 189,
    prerequisites: ['ECE 20002', 'MA 26600'], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['signals', 'communications', 'ml'],
    interestTags: ['math', 'dsp', 'theory'], level: 30000,
    professors: ['Mireille Boutin', 'Charlie Bouman', 'Ilias Bilionis'], typicalDays: ['MWF', 'TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 12, B: 22, C: 34, D: 18, F: 14 },
    reviews: [
      { id: 'r7', rating: 3, difficulty: 5, workload: 16, comment: 'Very math-heavy. Make sure your differential equations are solid.', professor: 'Mireille Boutin', semester: 'Fall 2024', source: 'BoilerGrades' },
      { id: 'r8', rating: 4, difficulty: 4, workload: 14, comment: 'Bouman explains things well. Watch the lecture recordings.', professor: 'Charlie Bouman', semester: 'Spring 2024', source: 'RateMyProfessor' },
    ]
  },
  {
    id: 'c8', code: 'ECE 30200', name: 'Probabilistic Methods in ECE', credits: 3,
    description: 'Probability theory, random variables, probability distributions, stochastic processes, and statistical inference for engineering applications.',
    avgGPA: 2.72, difficultyRating: 3.8, workloadHours: 13, reviewCount: 134,
    prerequisites: ['MA 26500'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['ml', 'signals', 'communications'],
    interestTags: ['math', 'statistics', 'theory'], level: 30000,
    professors: ['Mark Bell', 'James Lehnert'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 16, B: 26, C: 32, D: 16, F: 10 },
    reviews: [
      { id: 'r9', rating: 3, difficulty: 4, workload: 13, comment: 'Essential for ML track. Study the examples carefully.', professor: 'Mark Bell', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c9', code: 'ECE 30411', name: 'Electromagnetics I', credits: 3,
    description: 'Vector analysis, electrostatics, magnetostatics, and time-varying electromagnetic fields. Maxwells equations and wave propagation basics.',
    avgGPA: 2.65, difficultyRating: 4.0, workloadHours: 14, reviewCount: 112,
    prerequisites: ['PHYS 27200', 'MA 26200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['hardware', 'communications', 'rf'],
    interestTags: ['physics', 'math', 'theory'], level: 30000,
    professors: ['Dan Jiao', 'Peter Bermel'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 14, B: 24, C: 34, D: 17, F: 11 },
    reviews: []
  },
  // 36000-level courses
  {
    id: 'c10', code: 'ECE 36200', name: 'Microprocessor Systems and Interfacing', credits: 4,
    description: 'Microprocessor architecture, assembly language programming, hardware interfacing, interrupts, timers, and I/O peripherals using ARM processors.',
    avgGPA: 2.88, difficultyRating: 3.6, workloadHours: 15, reviewCount: 145,
    prerequisites: ['ECE 27000', 'ECE 26400'], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['embedded', 'hardware', 'software'],
    interestTags: ['architecture', 'programming', 'systems'], level: 36000,
    professors: ['James Krogmeier', 'Mark Johnson'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: true,
    requirementCategory: 'core',
    gradeDistribution: { A: 20, B: 32, C: 28, D: 12, F: 8 },
    reviews: [
      { id: 'r10', rating: 4, difficulty: 4, workload: 16, comment: 'Best course for learning embedded systems. Labs are long but rewarding.', professor: 'James Krogmeier', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c11', code: 'ECE 36800', name: 'Data Structures', credits: 3,
    description: 'Fundamental data structures including arrays, linked lists, stacks, queues, trees, graphs, hash tables, and algorithm analysis.',
    avgGPA: 2.95, difficultyRating: 3.4, workloadHours: 12, reviewCount: 167,
    prerequisites: ['ECE 26400'], corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['software'],
    interestTags: ['programming', 'algorithms'], level: 36000,
    professors: ['Yung-Hsiang Lu', 'Saurabh Bagchi'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 24, B: 30, C: 26, D: 12, F: 8 },
    reviews: [
      { id: 'r11', rating: 4, difficulty: 3, workload: 12, comment: 'Essential for software careers. Projects help understand concepts.', professor: 'Yung-Hsiang Lu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  // 40000-level courses
  {
    id: 'c12', code: 'ECE 40862', name: 'Software Testing', credits: 3,
    description: 'Software testing techniques, test-driven development, unit testing, integration testing, and test automation frameworks.',
    avgGPA: 3.18, difficultyRating: 2.9, workloadHours: 10, reviewCount: 87,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software'],
    interestTags: ['programming', 'quality'], level: 40000,
    professors: ['Xiangyu Zhang'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 32, B: 35, C: 22, D: 7, F: 4 },
    reviews: []
  },
  {
    id: 'c13', code: 'ECE 43700', name: 'Introduction to VLSI Design', credits: 3,
    description: 'MOS transistor theory, CMOS logic design, standard cell design methodology, layout techniques, and timing analysis.',
    avgGPA: 2.82, difficultyRating: 3.9, workloadHours: 14, reviewCount: 98,
    prerequisites: ['ECE 27000'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['circuits', 'digital', 'chip-design'], level: 43000,
    professors: ['Kaushik Roy', 'Sumeet Gupta'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 18, B: 30, C: 30, D: 14, F: 8 },
    reviews: [
      { id: 'r12', rating: 4, difficulty: 4, workload: 14, comment: 'Great intro to chip design. Cadence tools have a learning curve.', professor: 'Kaushik Roy', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c14', code: 'ECE 44000', name: 'Digital Integrated Circuits', credits: 3,
    description: 'Analysis and design of digital integrated circuits. CMOS inverter, logic gates, sequential circuits, and memory design.',
    avgGPA: 2.75, difficultyRating: 4.0, workloadHours: 14, reviewCount: 76,
    prerequisites: ['ECE 20002', 'ECE 27000'], corequisites: [],
    semesters: ['Fall'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['circuits', 'digital'], level: 44000,
    professors: ['Kaushik Roy'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 16, B: 26, C: 32, D: 16, F: 10 },
    reviews: []
  },
  {
    id: 'c15', code: 'ECE 46100', name: 'Software Engineering', credits: 3,
    description: 'Software development methodologies, requirements engineering, design patterns, testing, and project management. Agile and Scrum practices.',
    avgGPA: 3.15, difficultyRating: 2.8, workloadHours: 10, reviewCount: 112,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software'],
    interestTags: ['programming', 'teamwork', 'management'], level: 46000,
    professors: ['Xiaokang Qiu', 'James Davis'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 38, C: 22, D: 6, F: 4 },
    reviews: [
      { id: 'r13', rating: 4, difficulty: 2, workload: 10, comment: 'Good for learning industry practices. Team project is the main work.', professor: 'Xiaokang Qiu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c16', code: 'ECE 46300', name: 'Introduction to Computer Communication Networks', credits: 3,
    description: 'Network protocols, TCP/IP stack, routing, switching, and network security. Socket programming and network applications.',
    avgGPA: 2.98, difficultyRating: 3.3, workloadHours: 12, reviewCount: 134,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'communications'],
    interestTags: ['networking', 'systems'], level: 46000,
    professors: ['Sanjay Rao', 'Chunyi Peng'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 24, B: 32, C: 26, D: 12, F: 6 },
    reviews: []
  },
  {
    id: 'c17', code: 'ECE 46900', name: 'Object-Oriented Programming with C++', credits: 3,
    description: 'Object-oriented programming principles, C++ language features, templates, STL, and software design patterns.',
    avgGPA: 3.02, difficultyRating: 3.2, workloadHours: 12, reviewCount: 145,
    prerequisites: ['ECE 26400'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software'],
    interestTags: ['programming', 'design'], level: 46000,
    professors: ['Yung-Hsiang Lu'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 26, B: 32, C: 26, D: 10, F: 6 },
    reviews: []
  },
  // 49000-level courses
  {
    id: 'c18', code: 'ECE 49500', name: 'Introduction to Machine Learning', credits: 3,
    description: 'Fundamentals of machine learning including supervised and unsupervised learning, neural networks, decision trees, SVMs, and model evaluation.',
    avgGPA: 3.08, difficultyRating: 3.5, workloadHours: 13, reviewCount: 187,
    prerequisites: ['ECE 30200', 'ECE 20875'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math', 'ai'], level: 49000,
    professors: ['Stanley Chan', 'David Inouye'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 34, C: 24, D: 9, F: 5 },
    reviews: [
      { id: 'r14', rating: 5, difficulty: 3, workload: 12, comment: 'Excellent introduction to ML. Dr. Chan is a great teacher.', professor: 'Stanley Chan', semester: 'Fall 2024', source: 'BoilerGrades' },
      { id: 'r15', rating: 4, difficulty: 4, workload: 14, comment: 'Good balance of theory and practice. Projects are interesting.', professor: 'David Inouye', semester: 'Spring 2024', source: 'RateMyProfessor' },
    ]
  },
  {
    id: 'c19', code: 'ECE 49595', name: 'Computer Vision', credits: 3,
    description: 'Image processing, feature detection, object recognition, deep learning for vision, and 3D reconstruction.',
    avgGPA: 3.12, difficultyRating: 3.6, workloadHours: 13, reviewCount: 98,
    prerequisites: ['ECE 30100', 'ECE 20875'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'software', 'robotics'],
    interestTags: ['programming', 'math', 'vision'], level: 49000,
    professors: ['Avinash Kak', 'Qiang Qiu'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 32, C: 24, D: 9, F: 5 },
    reviews: []
  },
  // 50000-level courses (Graduate)
  {
    id: 'c20', code: 'ECE 50024', name: 'Machine Learning', credits: 3,
    description: 'Graduate-level machine learning covering theory and algorithms. PAC learning, VC dimension, kernel methods, and optimization.',
    avgGPA: 3.28, difficultyRating: 4.0, workloadHours: 15, reviewCount: 123,
    prerequisites: ['ECE 49500'], corequisites: [],
    semesters: ['Fall'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math', 'theory'], level: 50000,
    professors: ['David Inouye', 'Jean Honorio'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 35, B: 35, C: 20, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c21', code: 'ECE 50863', name: 'Deep Learning', credits: 3,
    description: 'Advanced deep learning architectures including CNNs, RNNs, transformers, GANs, and self-supervised learning. PyTorch implementation.',
    avgGPA: 3.22, difficultyRating: 3.6, workloadHours: 14, reviewCount: 156,
    prerequisites: ['ECE 49500'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math', 'ai'], level: 50000,
    professors: ['Qiang Qiu', 'Avinash Kak'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 34, B: 36, C: 20, D: 6, F: 4 },
    reviews: [
      { id: 'r16', rating: 5, difficulty: 4, workload: 14, comment: 'Hands-on deep learning. Project-based learning is effective.', professor: 'Qiang Qiu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c22', code: 'ECE 55900', name: 'Microprocessor Architectures', credits: 3,
    description: 'Advanced computer architecture including pipelining, caches, branch prediction, out-of-order execution, and multicore processors.',
    avgGPA: 2.92, difficultyRating: 3.7, workloadHours: 13, reviewCount: 89,
    prerequisites: ['ECE 36200'], corequisites: [],
    semesters: ['Fall'], careerTags: ['hardware', 'embedded', 'software'],
    interestTags: ['architecture', 'systems'], level: 55000,
    professors: ['Anand Raghunathan', 'Vijay Raghunathan'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 24, B: 34, C: 26, D: 10, F: 6 },
    reviews: []
  },
  {
    id: 'c23', code: 'ECE 57000', name: 'Artificial Intelligence', credits: 3,
    description: 'Classical AI including search algorithms, game playing, constraint satisfaction, logic, planning, and knowledge representation.',
    avgGPA: 3.05, difficultyRating: 3.5, workloadHours: 12, reviewCount: 134,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['ml', 'software', 'robotics'],
    interestTags: ['programming', 'theory', 'ai'], level: 57000,
    professors: ['Yung-Hsiang Lu'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 34, C: 24, D: 9, F: 5 },
    reviews: []
  },
  {
    id: 'c24', code: 'ECE 59500', name: 'Reinforcement Learning', credits: 3,
    description: 'Theory and applications of reinforcement learning including MDPs, Q-learning, policy gradient methods, and deep RL.',
    avgGPA: 3.18, difficultyRating: 3.8, workloadHours: 14, reviewCount: 76,
    prerequisites: ['ECE 49500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'robotics'],
    interestTags: ['math', 'programming', 'ai'], level: 59000,
    professors: ['Vaneet Aggarwal', 'Bruno Ribeiro'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 32, B: 36, C: 22, D: 6, F: 4 },
    reviews: [
      { id: 'r17', rating: 4, difficulty: 4, workload: 14, comment: 'Challenging but rewarding. Theory-heavy with good practical projects.', professor: 'Vaneet Aggarwal', semester: 'Spring 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c25', code: 'ECE 59500', name: 'Natural Language Processing', credits: 3,
    description: 'NLP fundamentals including text processing, language models, transformers, and applications like sentiment analysis and machine translation.',
    avgGPA: 3.15, difficultyRating: 3.5, workloadHours: 13, reviewCount: 67,
    prerequisites: ['ECE 49500'], corequisites: [],
    semesters: ['Fall'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'ai', 'language'], level: 59000,
    professors: ['Dan Goldwasser'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 38, C: 22, D: 6, F: 4 },
    reviews: []
  },
  // Additional core/required courses
  {
    id: 'c26', code: 'ECE 29401', name: 'Junior Seminar', credits: 0,
    description: 'Professional development seminar covering career planning, resume writing, technical communication, and ethics.',
    avgGPA: 3.85, difficultyRating: 1.2, workloadHours: 2, reviewCount: 245,
    prerequisites: [], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'hardware', 'ml'],
    interestTags: ['career', 'communication'], level: 29000,
    professors: ['Various Faculty'], typicalDays: ['W'],
    hasMorningSection: false, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: true,
    numExams: 0, isProjectBased: false, isExamBased: false, homeworkIntensity: 'light',
    isCodingHeavy: false, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 90, B: 8, C: 2, D: 0, F: 0 },
    reviews: []
  },
  {
    id: 'c27', code: 'ECE 39401', name: 'Senior Seminar', credits: 0,
    description: 'Continuation of professional development with focus on senior design preparation and career readiness.',
    avgGPA: 3.82, difficultyRating: 1.3, workloadHours: 2, reviewCount: 198,
    prerequisites: ['ECE 29401'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'hardware', 'ml'],
    interestTags: ['career', 'design'], level: 39000,
    professors: ['Various Faculty'], typicalDays: ['W'],
    hasMorningSection: false, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: true,
    numExams: 0, isProjectBased: false, isExamBased: false, homeworkIntensity: 'light',
    isCodingHeavy: false, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 88, B: 10, C: 2, D: 0, F: 0 },
    reviews: []
  },
  {
    id: 'c28', code: 'ECE 47700', name: 'Senior Design', credits: 3,
    description: 'Capstone design project. Teams design, build, and test an engineering system. Includes written and oral presentations.',
    avgGPA: 3.35, difficultyRating: 3.0, workloadHours: 12, reviewCount: 187,
    prerequisites: ['ECE 39401'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'hardware', 'embedded'],
    interestTags: ['design', 'teamwork', 'hands-on'], level: 47000,
    professors: ['Various Faculty'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: true,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'capstone',
    gradeDistribution: { A: 40, B: 40, C: 15, D: 4, F: 1 },
    reviews: [
      { id: 'r18', rating: 5, difficulty: 3, workload: 12, comment: 'Best class at Purdue. Actually build something real with your team.', professor: 'Various Faculty', semester: 'Spring 2024', source: 'BoilerGrades' },
    ]
  },
  // More electives
  {
    id: 'c29', code: 'ECE 56900', name: 'Introduction to Robotic Systems', credits: 3,
    description: 'Robot kinematics, dynamics, motion planning, control, and perception. Hands-on projects with robotic systems.',
    avgGPA: 3.08, difficultyRating: 3.4, workloadHours: 12, reviewCount: 87,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Fall'], careerTags: ['robotics', 'embedded', 'ml'],
    interestTags: ['programming', 'control', 'hands-on'], level: 56000,
    professors: ['Raymond DeCarlo'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 36, C: 24, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c30', code: 'ECE 53800', name: 'Digital Signal Processing', credits: 3,
    description: 'Digital filter design, FFT algorithms, multirate signal processing, and applications in audio and communications.',
    avgGPA: 2.78, difficultyRating: 3.9, workloadHours: 14, reviewCount: 112,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['signals', 'communications', 'embedded'],
    interestTags: ['dsp', 'math', 'programming'], level: 53000,
    professors: ['Charlie Bouman', 'Mireille Boutin'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 18, B: 28, C: 32, D: 14, F: 8 },
    reviews: []
  },
  {
    id: 'c31', code: 'ECE 60872', name: 'Fault-Tolerant Computer System Design', credits: 3,
    description: 'Reliability modeling, fault detection, error correction codes, and design of dependable systems.',
    avgGPA: 3.25, difficultyRating: 3.4, workloadHours: 12, reviewCount: 54,
    prerequisites: ['ECE 36200'], corequisites: [],
    semesters: ['Spring'], careerTags: ['hardware', 'embedded', 'software'],
    interestTags: ['systems', 'reliability'], level: 60000,
    professors: ['Saurabh Bagchi'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 35, B: 38, C: 20, D: 5, F: 2 },
    reviews: []
  },
  {
    id: 'c32', code: 'ECE 60146', name: 'Control Systems', credits: 3,
    description: 'Classical and modern control theory. State-space methods, stability analysis, and controller design.',
    avgGPA: 2.85, difficultyRating: 3.8, workloadHours: 13, reviewCount: 98,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['robotics', 'embedded', 'hardware'],
    interestTags: ['control', 'math', 'systems'], level: 60000,
    professors: ['Shreyas Sundaram', 'Inseok Hwang'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 20, B: 30, C: 30, D: 13, F: 7 },
    reviews: []
  },
  {
    id: 'c33', code: 'ECE 60827', name: 'Parallel Computing', credits: 3,
    description: 'Parallel algorithms, GPU programming with CUDA, distributed computing, and performance optimization.',
    avgGPA: 3.12, difficultyRating: 3.5, workloadHours: 13, reviewCount: 76,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall'], careerTags: ['software', 'ml', 'hardware'],
    interestTags: ['programming', 'systems', 'gpu'], level: 60000,
    professors: ['Milind Kulkarni'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 35, C: 24, D: 7, F: 4 },
    reviews: []
  },
  {
    id: 'c34', code: 'ECE 69500', name: 'Generative AI', credits: 3,
    description: 'Modern generative models including VAEs, GANs, diffusion models, and large language models. Theory and applications.',
    avgGPA: 3.32, difficultyRating: 3.7, workloadHours: 14, reviewCount: 45,
    prerequisites: ['ECE 50863'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'ai', 'research'], level: 69000,
    professors: ['Qiang Qiu'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 40, B: 38, C: 16, D: 4, F: 2 },
    reviews: []
  },
  {
    id: 'c35', code: 'ECE 50024', name: 'Statistical Machine Learning', credits: 3,
    description: 'Statistical foundations of machine learning. Bayesian methods, graphical models, and probabilistic inference.',
    avgGPA: 3.18, difficultyRating: 4.1, workloadHours: 15, reviewCount: 89,
    prerequisites: ['ECE 30200', 'ECE 49500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'software'],
    interestTags: ['math', 'statistics', 'theory'], level: 50000,
    professors: ['Jean Honorio'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 32, B: 36, C: 22, D: 6, F: 4 },
    reviews: []
  },
  // Additional 20000-level courses
  {
    id: 'c36', code: 'ECE 20008', name: 'Electrical Engineering Fundamentals Lab II', credits: 1,
    description: 'Laboratory experiments covering AC circuits, frequency response, and filter design.',
    avgGPA: 3.42, difficultyRating: 2.3, workloadHours: 4, reviewCount: 94,
    prerequisites: ['ECE 20007'], corequisites: ['ECE 20002'],
    semesters: ['Fall', 'Spring', 'Summer'], careerTags: ['hardware', 'signals'],
    interestTags: ['circuits', 'hands-on'], level: 20000,
    professors: ['Lab Staff'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: true,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'light',
    isCodingHeavy: false, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: true,
    requirementCategory: 'core',
    gradeDistribution: { A: 44, B: 36, C: 15, D: 3, F: 2 },
    reviews: []
  },
  {
    id: 'c37', code: 'ECE 25500', name: 'Introduction to Electronic Analysis and Design', credits: 3,
    description: 'Analysis and design of electronic circuits using diodes, BJTs, and MOSFETs. Amplifier configurations and frequency response.',
    avgGPA: 2.72, difficultyRating: 3.6, workloadHours: 13, reviewCount: 134,
    prerequisites: ['ECE 20002'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['hardware', 'vlsi', 'analog'],
    interestTags: ['circuits', 'analog', 'electronics'], level: 25000,
    professors: ['Byunghoo Jung', 'Saeed Mohammadi'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: true, isTechElective: false, isGenEd: false, isLabCredit: false,
    requirementCategory: 'core',
    gradeDistribution: { A: 16, B: 26, C: 32, D: 16, F: 10 },
    reviews: [
      { id: 'r19', rating: 3, difficulty: 4, workload: 13, comment: 'Transistors are tricky. Practice lots of problems.', professor: 'Byunghoo Jung', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c38', code: 'ECE 25700', name: 'Digital Electronics Lab', credits: 1,
    description: 'Hands-on experiments with digital circuits, logic gates, flip-flops, and FPGA programming.',
    avgGPA: 3.38, difficultyRating: 2.5, workloadHours: 5, reviewCount: 112,
    prerequisites: ['ECE 27000'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['hardware', 'embedded', 'vlsi'],
    interestTags: ['digital', 'hands-on', 'fpga'], level: 25000,
    professors: ['Lab Staff'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: true,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: true,
    requirementCategory: 'breadth',
    gradeDistribution: { A: 42, B: 35, C: 17, D: 4, F: 2 },
    reviews: []
  },
  // More 30000-level courses
  {
    id: 'c39', code: 'ECE 30412', name: 'Electromagnetics II', credits: 3,
    description: 'Wave propagation, transmission lines, waveguides, antennas, and electromagnetic radiation.',
    avgGPA: 2.58, difficultyRating: 4.2, workloadHours: 15, reviewCount: 98,
    prerequisites: ['ECE 30411'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['rf', 'communications', 'hardware'],
    interestTags: ['physics', 'math', 'wireless'], level: 30000,
    professors: ['Dan Jiao', 'Dimitrios Peroulis'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 12, B: 22, C: 36, D: 18, F: 12 },
    reviews: []
  },
  {
    id: 'c40', code: 'ECE 31100', name: 'Electric and Magnetic Fields', credits: 3,
    description: 'Static electric and magnetic fields, boundary value problems, and introduction to electromagnetic waves.',
    avgGPA: 2.68, difficultyRating: 3.9, workloadHours: 14, reviewCount: 87,
    prerequisites: ['PHYS 27200', 'MA 26200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['hardware', 'rf'],
    interestTags: ['physics', 'math'], level: 31000,
    professors: ['Peter Bermel'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 15, B: 25, C: 34, D: 16, F: 10 },
    reviews: []
  },
  {
    id: 'c41', code: 'ECE 32300', name: 'Electromechanical Motion Devices', credits: 3,
    description: 'Principles of electromechanical energy conversion, DC and AC machines, transformers, and stepper motors.',
    avgGPA: 2.82, difficultyRating: 3.5, workloadHours: 12, reviewCount: 76,
    prerequisites: ['ECE 20002'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['power', 'hardware', 'robotics'],
    interestTags: ['motors', 'energy', 'systems'], level: 32000,
    professors: ['Scott Sudhoff', 'Steven Pekarek'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 20, B: 30, C: 30, D: 12, F: 8 },
    reviews: []
  },
  {
    id: 'c42', code: 'ECE 33300', name: 'Power Electronics', credits: 3,
    description: 'Power semiconductor devices, DC-DC converters, inverters, and motor drives.',
    avgGPA: 2.75, difficultyRating: 3.7, workloadHours: 13, reviewCount: 65,
    prerequisites: ['ECE 20002'], corequisites: [],
    semesters: ['Fall'], careerTags: ['power', 'hardware', 'embedded'],
    interestTags: ['circuits', 'energy', 'electronics'], level: 33000,
    professors: ['Dionysios Aliprantis'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 18, B: 28, C: 32, D: 14, F: 8 },
    reviews: []
  },
  // More 36000-level courses
  {
    id: 'c43', code: 'ECE 36400', name: 'Software Engineering Tools Laboratory', credits: 1,
    description: 'Hands-on experience with version control, build systems, testing frameworks, and CI/CD.',
    avgGPA: 3.52, difficultyRating: 2.2, workloadHours: 4, reviewCount: 145,
    prerequisites: ['ECE 26400'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software'],
    interestTags: ['programming', 'devops', 'tools'], level: 36000,
    professors: ['Lab Staff'], typicalDays: ['W'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: true,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: true,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'light',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: true,
    requirementCategory: 'breadth',
    gradeDistribution: { A: 55, B: 30, C: 12, D: 2, F: 1 },
    reviews: []
  },
  // More 40000-level courses
  {
    id: 'c44', code: 'ECE 40400', name: 'Introduction to Computer Security', credits: 3,
    description: 'Security principles, cryptography, authentication, network security, and secure software development.',
    avgGPA: 3.05, difficultyRating: 3.2, workloadHours: 11, reviewCount: 123,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'security'],
    interestTags: ['security', 'networking', 'systems'], level: 40000,
    professors: ['Dongyan Xu', 'Christina Garman'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 35, C: 25, D: 8, F: 4 },
    reviews: [
      { id: 'r20', rating: 4, difficulty: 3, workload: 11, comment: 'Interesting content. CTF challenges are fun.', professor: 'Dongyan Xu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c45', code: 'ECE 40500', name: 'Random Signals', credits: 3,
    description: 'Random processes, power spectral density, linear systems with random inputs, and optimal filtering.',
    avgGPA: 2.62, difficultyRating: 4.1, workloadHours: 14, reviewCount: 87,
    prerequisites: ['ECE 30100', 'ECE 30200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['signals', 'communications', 'ml'],
    interestTags: ['math', 'statistics', 'dsp'], level: 40000,
    professors: ['Mark Bell', 'James Lehnert'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 14, B: 24, C: 34, D: 18, F: 10 },
    reviews: []
  },
  {
    id: 'c46', code: 'ECE 41200', name: 'Integrated Circuit Engineering', credits: 3,
    description: 'IC fabrication processes, semiconductor physics, device modeling, and process simulation.',
    avgGPA: 2.88, difficultyRating: 3.6, workloadHours: 12, reviewCount: 54,
    prerequisites: ['ECE 25500'], corequisites: [],
    semesters: ['Fall'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['fabrication', 'physics', 'devices'], level: 41000,
    professors: ['Muhammad Alam', 'Peide Ye'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: false, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 22, B: 32, C: 28, D: 12, F: 6 },
    reviews: []
  },
  {
    id: 'c47', code: 'ECE 43800', name: 'VLSI Testing', credits: 3,
    description: 'Test generation, fault modeling, design for testability, and built-in self-test techniques.',
    avgGPA: 3.02, difficultyRating: 3.4, workloadHours: 11, reviewCount: 43,
    prerequisites: ['ECE 43700'], corequisites: [],
    semesters: ['Spring'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital', 'testing', 'design'], level: 43000,
    professors: ['Anand Raghunathan'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 26, B: 36, C: 26, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c48', code: 'ECE 44100', name: 'Analog Integrated Circuits', credits: 3,
    description: 'Design of CMOS analog circuits including amplifiers, current mirrors, and operational amplifiers.',
    avgGPA: 2.68, difficultyRating: 4.1, workloadHours: 14, reviewCount: 67,
    prerequisites: ['ECE 25500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['vlsi', 'hardware', 'analog'],
    interestTags: ['circuits', 'analog', 'design'], level: 44000,
    professors: ['Byunghoo Jung', 'Chen Yang'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 14, B: 26, C: 34, D: 16, F: 10 },
    reviews: []
  },
  {
    id: 'c49', code: 'ECE 45600', name: 'Digital Communications', credits: 3,
    description: 'Digital modulation, channel coding, detection theory, and communication system performance analysis.',
    avgGPA: 2.72, difficultyRating: 3.9, workloadHours: 13, reviewCount: 78,
    prerequisites: ['ECE 30100', 'ECE 30200'], corequisites: [],
    semesters: ['Fall'], careerTags: ['communications', 'signals'],
    interestTags: ['wireless', 'math', 'dsp'], level: 45000,
    professors: ['James Lehnert', 'David Love'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 16, B: 28, C: 32, D: 15, F: 9 },
    reviews: []
  },
  {
    id: 'c50', code: 'ECE 46800', name: 'Compilers and Translation Engineering', credits: 3,
    description: 'Lexical analysis, parsing, semantic analysis, code generation, and optimization techniques.',
    avgGPA: 2.92, difficultyRating: 3.6, workloadHours: 14, reviewCount: 89,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall'], careerTags: ['software'],
    interestTags: ['programming', 'theory', 'systems'], level: 46000,
    professors: ['Milind Kulkarni', 'Tiark Rompf'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 24, B: 32, C: 26, D: 12, F: 6 },
    reviews: []
  },
  {
    id: 'c51', code: 'ECE 47300', name: 'Introduction to Nanotechnology', credits: 3,
    description: 'Fundamentals of nanoscience, quantum mechanics for nanostructures, and nanodevice applications.',
    avgGPA: 3.12, difficultyRating: 3.3, workloadHours: 11, reviewCount: 56,
    prerequisites: ['PHYS 27200'], corequisites: [],
    semesters: ['Spring'], careerTags: ['hardware', 'vlsi'],
    interestTags: ['physics', 'research', 'devices'], level: 47000,
    professors: ['Muhammad Alam', 'Zhihong Chen'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: false, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 36, C: 22, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c52', code: 'ECE 47500', name: 'Introduction to Information Theory', credits: 3,
    description: 'Entropy, mutual information, channel capacity, source coding, and rate-distortion theory.',
    avgGPA: 2.78, difficultyRating: 4.0, workloadHours: 13, reviewCount: 54,
    prerequisites: ['ECE 30200'], corequisites: [],
    semesters: ['Fall'], careerTags: ['communications', 'ml'],
    interestTags: ['math', 'theory', 'information'], level: 47000,
    professors: ['Mark Bell'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 18, B: 28, C: 32, D: 14, F: 8 },
    reviews: []
  },
  // More 50000-level courses
  {
    id: 'c53', code: 'ECE 50026', name: 'Introduction to Radar Systems', credits: 3,
    description: 'Radar fundamentals, waveform design, detection theory, and signal processing for radar.',
    avgGPA: 3.08, difficultyRating: 3.5, workloadHours: 12, reviewCount: 45,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Spring'], careerTags: ['signals', 'communications', 'rf'],
    interestTags: ['dsp', 'wireless', 'defense'], level: 50000,
    professors: ['Mark Bell'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 36, C: 24, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c54', code: 'ECE 50864', name: 'Image Processing', credits: 3,
    description: 'Image enhancement, restoration, segmentation, morphological operations, and compression.',
    avgGPA: 3.15, difficultyRating: 3.4, workloadHours: 12, reviewCount: 87,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['ml', 'signals', 'software'],
    interestTags: ['programming', 'vision', 'dsp'], level: 50000,
    professors: ['Charlie Bouman', 'Mireille Boutin'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 32, B: 36, C: 22, D: 6, F: 4 },
    reviews: [
      { id: 'r21', rating: 5, difficulty: 3, workload: 12, comment: 'Bouman is amazing. Great practical applications.', professor: 'Charlie Bouman', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c55', code: 'ECE 50868', name: 'Medical Imaging Systems', credits: 3,
    description: 'Physics and engineering of medical imaging including X-ray, CT, MRI, and ultrasound.',
    avgGPA: 3.22, difficultyRating: 3.3, workloadHours: 11, reviewCount: 43,
    prerequisites: ['ECE 30100'], corequisites: [],
    semesters: ['Spring'], careerTags: ['signals', 'ml'],
    interestTags: ['medical', 'physics', 'imaging'], level: 50000,
    professors: ['Charlie Bouman'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 35, B: 38, C: 20, D: 5, F: 2 },
    reviews: []
  },
  {
    id: 'c56', code: 'ECE 50879', name: 'Wireless Networks and Mobile Systems', credits: 3,
    description: 'Cellular networks, WiFi, Bluetooth, mobile computing, and IoT protocols.',
    avgGPA: 3.12, difficultyRating: 3.3, workloadHours: 11, reviewCount: 67,
    prerequisites: ['ECE 46300'], corequisites: [],
    semesters: ['Fall'], careerTags: ['communications', 'software', 'embedded'],
    interestTags: ['networking', 'wireless', 'iot'], level: 50000,
    professors: ['Chunyi Peng', 'Sanjay Rao'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 36, C: 24, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c57', code: 'ECE 51200', name: 'Numerical Software Development', credits: 3,
    description: 'Numerical methods, linear algebra algorithms, optimization, and scientific computing.',
    avgGPA: 3.08, difficultyRating: 3.4, workloadHours: 12, reviewCount: 56,
    prerequisites: ['MA 26500'], corequisites: [],
    semesters: ['Fall'], careerTags: ['software', 'ml'],
    interestTags: ['math', 'programming', 'hpc'], level: 51000,
    professors: ['Ananth Grama'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 36, C: 26, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c58', code: 'ECE 51800', name: 'Introduction to AI Engineering', credits: 3,
    description: 'Building production AI systems, MLOps, model deployment, and AI system design.',
    avgGPA: 3.28, difficultyRating: 3.2, workloadHours: 12, reviewCount: 34,
    prerequisites: ['ECE 49500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'ai', 'systems'], level: 51000,
    professors: ['Yung-Hsiang Lu'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 38, B: 38, C: 18, D: 4, F: 2 },
    reviews: []
  },
  {
    id: 'c59', code: 'ECE 52300', name: 'Power System Analysis', credits: 3,
    description: 'Power flow, fault analysis, economic dispatch, and power system stability.',
    avgGPA: 2.85, difficultyRating: 3.6, workloadHours: 12, reviewCount: 45,
    prerequisites: ['ECE 32300'], corequisites: [],
    semesters: ['Fall'], careerTags: ['power', 'hardware'],
    interestTags: ['energy', 'systems', 'grid'], level: 52000,
    professors: ['Steven Pekarek', 'Dionysios Aliprantis'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 20, B: 32, C: 30, D: 12, F: 6 },
    reviews: []
  },
  {
    id: 'c60', code: 'ECE 52500', name: 'Renewable Electric Energy Systems', credits: 3,
    description: 'Solar, wind, and energy storage systems integration with the electric grid.',
    avgGPA: 3.15, difficultyRating: 3.2, workloadHours: 11, reviewCount: 38,
    prerequisites: ['ECE 32300'], corequisites: [],
    semesters: ['Spring'], careerTags: ['power', 'hardware'],
    interestTags: ['energy', 'sustainability', 'grid'], level: 52000,
    professors: ['Dionysios Aliprantis'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 32, B: 38, C: 22, D: 5, F: 3 },
    reviews: []
  },
  {
    id: 'c61', code: 'ECE 53600', name: 'Microwave Remote Sensing', credits: 3,
    description: 'Radar and radiometer systems for Earth observation and remote sensing applications.',
    avgGPA: 3.05, difficultyRating: 3.5, workloadHours: 12, reviewCount: 32,
    prerequisites: ['ECE 30412'], corequisites: [],
    semesters: ['Fall'], careerTags: ['rf', 'signals'],
    interestTags: ['physics', 'remote-sensing', 'earth'], level: 53000,
    professors: ['James Garrison'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 38, C: 24, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c62', code: 'ECE 54200', name: 'Network Design', credits: 3,
    description: 'Advanced network protocols, software-defined networking, and network virtualization.',
    avgGPA: 3.02, difficultyRating: 3.4, workloadHours: 12, reviewCount: 54,
    prerequisites: ['ECE 46300'], corequisites: [],
    semesters: ['Spring'], careerTags: ['software', 'communications'],
    interestTags: ['networking', 'systems', 'cloud'], level: 54000,
    professors: ['Sanjay Rao'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 26, B: 38, C: 26, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c63', code: 'ECE 55000', name: 'Fundamentals of Nanoelectronics', credits: 3,
    description: 'Quantum mechanics for nanodevices, ballistic transport, and emerging transistor technologies.',
    avgGPA: 2.75, difficultyRating: 4.2, workloadHours: 14, reviewCount: 45,
    prerequisites: ['ECE 30500'], corequisites: [],
    semesters: ['Fall'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['physics', 'quantum', 'devices'], level: 55000,
    professors: ['Muhammad Alam', 'Supriyo Datta'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 16, B: 28, C: 34, D: 14, F: 8 },
    reviews: []
  },
  {
    id: 'c64', code: 'ECE 55200', name: 'Introduction to Lasers', credits: 3,
    description: 'Laser physics, optical resonators, semiconductor lasers, and photonic devices.',
    avgGPA: 2.88, difficultyRating: 3.7, workloadHours: 12, reviewCount: 38,
    prerequisites: ['ECE 30500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['hardware', 'communications'],
    interestTags: ['physics', 'optics', 'photonics'], level: 55000,
    professors: ['Minghao Qi'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: false, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 22, B: 34, C: 28, D: 10, F: 6 },
    reviews: []
  },
  {
    id: 'c65', code: 'ECE 56500', name: 'Introduction to Computer Architecture', credits: 3,
    description: 'Instruction set architecture, pipelining, memory hierarchy, and parallel architectures.',
    avgGPA: 2.95, difficultyRating: 3.5, workloadHours: 13, reviewCount: 98,
    prerequisites: ['ECE 36200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['hardware', 'embedded', 'software'],
    interestTags: ['architecture', 'systems', 'performance'], level: 56000,
    professors: ['T.N. Vijaykumar', 'Mithuna Thottethodi'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 24, B: 34, C: 26, D: 10, F: 6 },
    reviews: [
      { id: 'r22', rating: 4, difficulty: 4, workload: 13, comment: 'Challenging but excellent for understanding how CPUs work.', professor: 'T.N. Vijaykumar', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c66', code: 'ECE 57300', name: 'Computer Operating Systems', credits: 3,
    description: 'Process management, memory management, file systems, and distributed systems.',
    avgGPA: 2.88, difficultyRating: 3.6, workloadHours: 14, reviewCount: 112,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software', 'systems'],
    interestTags: ['systems', 'programming', 'os'], level: 57000,
    professors: ['Dongyan Xu', 'Pedro Fonseca'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 22, B: 32, C: 28, D: 12, F: 6 },
    reviews: [
      { id: 'r23', rating: 4, difficulty: 4, workload: 14, comment: 'Kernel projects are tough but you learn a lot.', professor: 'Dongyan Xu', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
  {
    id: 'c67', code: 'ECE 57800', name: 'Database Systems', credits: 3,
    description: 'Relational databases, SQL, query optimization, transaction processing, and NoSQL systems.',
    avgGPA: 3.05, difficultyRating: 3.3, workloadHours: 12, reviewCount: 78,
    prerequisites: ['ECE 36800'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['software'],
    interestTags: ['programming', 'data', 'systems'], level: 57000,
    professors: ['Walid Aref', 'Bharat Bhargava'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 28, B: 36, C: 24, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c68', code: 'ECE 58000', name: 'Introduction to Embedded Systems', credits: 3,
    description: 'Real-time systems, embedded software design, RTOS, and hardware-software co-design.',
    avgGPA: 3.02, difficultyRating: 3.4, workloadHours: 13, reviewCount: 89,
    prerequisites: ['ECE 36200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['embedded', 'hardware', 'software'],
    interestTags: ['systems', 'programming', 'real-time'], level: 58000,
    professors: ['Vijay Raghunathan', 'Saurabh Bagchi'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 26, B: 36, C: 26, D: 8, F: 4 },
    reviews: []
  },
  {
    id: 'c69', code: 'ECE 58100', name: 'Hardware/Software Co-Design', credits: 3,
    description: 'System-level design, hardware accelerators, FPGA prototyping, and co-simulation.',
    avgGPA: 3.12, difficultyRating: 3.5, workloadHours: 13, reviewCount: 56,
    prerequisites: ['ECE 43700', 'ECE 36200'], corequisites: [],
    semesters: ['Spring'], careerTags: ['embedded', 'hardware', 'vlsi'],
    interestTags: ['fpga', 'systems', 'design'], level: 58000,
    professors: ['Anand Raghunathan'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 30, B: 38, C: 22, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c70', code: 'ECE 59500', name: 'IoT Systems', credits: 3,
    description: 'Internet of Things architectures, sensor networks, edge computing, and IoT security.',
    avgGPA: 3.18, difficultyRating: 3.2, workloadHours: 11, reviewCount: 67,
    prerequisites: ['ECE 36200'], corequisites: [],
    semesters: ['Fall'], careerTags: ['embedded', 'software', 'communications'],
    interestTags: ['iot', 'networking', 'sensors'], level: 59000,
    professors: ['Saurabh Bagchi', 'Vijay Raghunathan'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 1, isProjectBased: true, isExamBased: false, homeworkIntensity: 'moderate',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 34, B: 38, C: 20, D: 5, F: 3 },
    reviews: []
  },
  {
    id: 'c71', code: 'ECE 60822', name: 'Advanced Computer Architecture', credits: 3,
    description: 'Superscalar processors, multithreading, cache coherence, and memory consistency models.',
    avgGPA: 3.02, difficultyRating: 3.8, workloadHours: 14, reviewCount: 45,
    prerequisites: ['ECE 56500'], corequisites: [],
    semesters: ['Spring'], careerTags: ['hardware', 'software'],
    interestTags: ['architecture', 'performance', 'systems'], level: 60000,
    professors: ['T.N. Vijaykumar'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: false, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 26, B: 38, C: 26, D: 6, F: 4 },
    reviews: []
  },
  {
    id: 'c72', code: 'ECE 60878', name: 'Advanced Graph Neural Networks', credits: 3,
    description: 'GNN architectures, message passing, graph transformers, and applications.',
    avgGPA: 3.25, difficultyRating: 3.6, workloadHours: 13, reviewCount: 28,
    prerequisites: ['ECE 50863'], corequisites: [],
    semesters: ['Spring'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'ai', 'graphs'], level: 60000,
    professors: ['Bruno Ribeiro'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 38, B: 40, C: 16, D: 4, F: 2 },
    reviews: []
  },
  {
    id: 'c73', code: 'ECE 60000', name: 'Random Variables and Signals', credits: 3,
    description: 'Graduate probability theory, stochastic processes, and estimation theory.',
    avgGPA: 2.68, difficultyRating: 4.2, workloadHours: 15, reviewCount: 112,
    prerequisites: ['ECE 30200'], corequisites: [],
    semesters: ['Fall', 'Spring'], careerTags: ['signals', 'ml', 'communications'],
    interestTags: ['math', 'statistics', 'theory'], level: 60000,
    professors: ['Mark Bell', 'David Love'], typicalDays: ['MWF'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: true, hasOnlineOption: false, hasHybridOption: false,
    numExams: 3, isProjectBased: false, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: false, isMathHeavy: true, examIntensity: 'high', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 15, B: 25, C: 35, D: 15, F: 10 },
    reviews: []
  },
  {
    id: 'c74', code: 'ECE 64700', name: 'Advanced VLSI Design', credits: 3,
    description: 'Low-power design, high-speed circuits, and advanced CMOS technologies.',
    avgGPA: 2.92, difficultyRating: 4.0, workloadHours: 14, reviewCount: 43,
    prerequisites: ['ECE 43700'], corequisites: [],
    semesters: ['Spring'], careerTags: ['vlsi', 'hardware'],
    interestTags: ['circuits', 'design', 'chips'], level: 64000,
    professors: ['Kaushik Roy', 'Sumeet Gupta'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: false, hasHybridOption: false,
    numExams: 2, isProjectBased: true, isExamBased: true, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'medium', hasGroupProjects: false,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 24, B: 34, C: 28, D: 10, F: 4 },
    reviews: []
  },
  {
    id: 'c75', code: 'ECE 69500', name: 'Large Language Models', credits: 3,
    description: 'Transformer architectures, pretraining, fine-tuning, RLHF, and LLM applications.',
    avgGPA: 3.35, difficultyRating: 3.5, workloadHours: 13, reviewCount: 56,
    prerequisites: ['ECE 50863'], corequisites: [],
    semesters: ['Fall'], careerTags: ['ml', 'software'],
    interestTags: ['programming', 'ai', 'nlp'], level: 69000,
    professors: ['Dan Goldwasser', 'David Inouye'], typicalDays: ['TR'],
    hasMorningSection: true, hasAfternoonSection: true, hasEveningSection: false,
    hasFridayClass: false, hasOnlineOption: true, hasHybridOption: false,
    numExams: 0, isProjectBased: true, isExamBased: false, homeworkIntensity: 'heavy',
    isCodingHeavy: true, isMathHeavy: true, examIntensity: 'low', hasGroupProjects: true,
    isMajorRequirement: false, isTechElective: true, isGenEd: false, isLabCredit: false,
    requirementCategory: 'depth',
    gradeDistribution: { A: 42, B: 38, C: 15, D: 3, F: 2 },
    reviews: [
      { id: 'r24', rating: 5, difficulty: 3, workload: 13, comment: 'Cutting-edge content. Great for anyone interested in AI.', professor: 'Dan Goldwasser', semester: 'Fall 2024', source: 'BoilerGrades' },
    ]
  },
];

// Helper function to find a course by code
export function findCourseByCode(code: string): DemoCourse | undefined {
  return DEMO_COURSES.find(c => c.code.toLowerCase() === code.toLowerCase());
}

// Helper function to get courses count
export function getCourseCount(): number {
  return DEMO_COURSES.length;
}
