-- Simple seed data for courses
INSERT INTO "Course" (id, code, name, credits, description, prerequisites, corequisites, "avgGPA", "difficultyRating", "workloadHours", "reviewCount", semesters, department, level, "careerTags", "interestTags", professors, "typicalDays", "hasMorningSection", "hasAfternoonSection", "hasEveningSection", "hasFridayClass", "hasOnlineOption", "hasHybridOption", "numExams", "isProjectBased", "isExamBased", "homeworkIntensity", "isCodingHeavy", "isMathHeavy", "examIntensity", "hasGroupProjects", "isMajorRequirement", "isTechElective", "isGenEd", "isLabCredit", "requirementCategory", "createdAt", "updatedAt") VALUES
('c1', 'ECE 20001', 'Electrical Engineering Fundamentals I', 3, 'Introduction to electrical engineering concepts. Basic circuit elements, Kirchhoffs laws, nodal and mesh analysis.', '{"PHYS 17200","MA 26100"}', '{"ECE 20007"}', 2.85, 3.2, 12, 0, '{Fall,Spring,Summer}', 'ECE', 20000, '{hardware,embedded,signals}', '{circuits,physics,analog}', '{Mark Johnson,Shreyas Sen}', '{MWF,TR}', true, true, false, true, false, false, 3, false, true, 'heavy', false, true, 'high', false, true, false, false, false, 'core', NOW(), NOW()),
('c2', 'ECE 20002', 'Electrical Engineering Fundamentals II', 3, 'Second-order transient response, sinusoidal steady-state response, AC power analysis.', '{"ECE 20001"}', '{"ECE 20008"}', 2.78, 3.4, 13, 0, '{Fall,Spring,Summer}', 'ECE', 20000, '{hardware,signals,power}', '{circuits,analog,physics}', '{Mark Johnson,Shreyas Sen}', '{MWF,TR}', true, true, false, true, false, false, 3, false, true, 'heavy', false, true, 'high', false, true, false, false, false, 'core', NOW(), NOW()),
('c3', 'ECE 27000', 'Introduction to Digital System Design', 4, 'Boolean algebra, combinational and sequential logic design, finite state machines, programmable logic.', '{}', '{}', 2.95, 3.3, 14, 0, '{Fall,Spring,Summer}', 'ECE', 27000, '{hardware,embedded,vlsi}', '{digital,circuits}', '{Cheng-Kok Koh}', '{MWF}', true, true, false, true, false, false, 3, true, true, 'heavy', true, false, 'medium', true, true, false, false, true, 'core', NOW(), NOW()),
('c4', 'ECE 30100', 'Signals and Systems', 3, 'Continuous and discrete-time signals and systems. Convolution, Fourier series, Fourier transform, Laplace transform.', '{"ECE 20002","MA 26600"}', '{}', 2.58, 4.2, 15, 0, '{Fall,Spring,Summer}', 'ECE', 30000, '{signals,communications,ml}', '{math,dsp}', '{Mireille Boutin,Charlie Bouman}', '{MWF,TR}', true, true, false, true, false, false, 3, false, true, 'heavy', false, true, 'high', false, true, false, false, false, 'core', NOW(), NOW()),
('c5', 'ECE 36200', 'Microprocessor Systems and Interfacing', 4, 'Microprocessor architecture, assembly language programming, hardware interfacing.', '{"ECE 27000","ECE 26400"}', '{}', 2.88, 3.6, 15, 0, '{Fall,Spring,Summer}', 'ECE', 36000, '{embedded,hardware,software}', '{architecture,programming}', '{James Krogmeier}', '{MWF}', true, true, false, true, false, false, 2, true, true, 'heavy', true, false, 'medium', true, true, false, false, true, 'core', NOW(), NOW()),
('c6', 'ECE 36800', 'Data Structures', 3, 'Fundamental data structures: arrays, linked lists, stacks, queues, trees, graphs.', '{"ECE 26400"}', '{}', 2.95, 3.4, 12, 0, '{Fall,Spring,Summer}', 'ECE', 36000, '{software}', '{programming}', '{Yung-Hsiang Lu}', '{TR}', true, true, false, false, true, false, 2, true, true, 'heavy', true, false, 'medium', false, true, false, false, false, 'core', NOW(), NOW()),
('c7', 'ECE 49500', 'Introduction to Machine Learning', 3, 'Fundamentals of machine learning. Supervised and unsupervised learning, neural networks.', '{"ECE 30200","ECE 20875"}', '{}', 3.08, 3.5, 13, 0, '{Fall,Spring}', 'ECE', 49000, '{ml,software}', '{programming,math}', '{Stanley Chan,David Inouye}', '{TR}', true, true, false, false, true, false, 2, true, true, 'heavy', true, true, 'medium', true, false, true, false, false, 'depth', NOW(), NOW()),
('c8', 'ECE 50863', 'Deep Learning', 3, 'Advanced deep learning. CNNs, RNNs, transformers, GANs.', '{"ECE 49500"}', '{}', 3.22, 3.6, 14, 0, '{Fall,Spring}', 'ECE', 50000, '{ml,software}', '{programming,math}', '{Qiang Qiu}', '{TR}', true, true, false, false, true, false, 1, true, false, 'heavy', true, true, 'low', true, false, true, false, false, 'depth', NOW(), NOW()),
('c9', 'ECE 20875', 'Python for Data Science', 3, 'Introduction to Python programming with applications in data analysis.', '{}', '{}', 3.25, 2.5, 10, 0, '{Fall,Spring,Summer}', 'ECE', 20000, '{software,ml}', '{programming,math}', '{David Inouye,Stanley Chan}', '{TR}', true, true, false, false, true, true, 2, true, true, 'moderate', true, false, 'medium', false, false, true, false, false, 'breadth', NOW(), NOW()),
('c10', 'ECE 26400', 'Advanced C Programming', 3, 'Advanced C programming concepts including pointers, dynamic memory allocation.', '{"CS 15900"}', '{}', 2.92, 3.5, 14, 0, '{Fall,Spring,Summer}', 'ECE', 26000, '{software,embedded}', '{programming}', '{Yung-Hsiang Lu}', '{TR}', true, true, false, false, true, false, 2, true, true, 'heavy', true, false, 'medium', false, true, false, false, false, 'core', NOW(), NOW());
