// Additional ECE courses to add to the database
// These will be merged with the existing seed data

export const ADDITIONAL_COURSES = [
  // ==================== 10000-20000 LEVEL ====================
  {
    code: 'ECE 15200',
    name: 'Programming For Engineers',
    credits: 3,
    description: 'Introduction to programming concepts for engineering students. Problem solving, algorithms, and basic data structures.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 15000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: false,
    requirementCategory: null,
  },
  {
    code: 'ECE 20400',
    name: 'Introduction To Electrical And Electronic Circuits',
    credits: 4,
    description: 'Introduction to electrical circuits for non-ECE majors. DC and AC circuit analysis, operational amplifiers, and digital logic basics.',
    prerequisites: ['PHYS 17200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware'],
    interestTags: ['circuits'],
    isMajorRequirement: false,
    isTechElective: false,
    requirementCategory: null,
  },
  {
    code: 'ECE 20700',
    name: 'Electronic Measurement Techniques',
    credits: 1,
    description: 'Laboratory techniques for electronic measurements. Oscilloscopes, multimeters, signal generators, and data acquisition.',
    prerequisites: [],
    corequisites: ['ECE 20001'],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware'],
    interestTags: ['circuits'],
    isMajorRequirement: false,
    isTechElective: false,
    isLabCredit: true,
    requirementCategory: null,
  },
  {
    code: 'ECE 22900',
    name: 'C Programming For Electrical And Computer Engineering',
    credits: 3,
    description: 'Introduction to C programming for ECE students. Variables, control structures, functions, pointers, and basic data structures.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 22000,
    careerTags: ['software', 'embedded'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 25100',
    name: 'Object Oriented Programming',
    credits: 3,
    description: 'Object-oriented programming concepts. Classes, inheritance, polymorphism, and design patterns.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 25000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'breadth',
  },
  // ==================== 30000 LEVEL ====================
  {
    code: 'ECE 30010',
    name: 'Introduction To Machine Learning And Pattern Recognition',
    credits: 3,
    description: 'Fundamentals of machine learning and pattern recognition. Classification, regression, clustering, and neural networks.',
    prerequisites: ['ECE 30200', 'ECE 20875'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30300',
    name: 'Engineering Software Design',
    credits: 3,
    description: 'Software design principles for engineers. Requirements, architecture, testing, and maintenance.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 30414',
    name: 'Elements Of Fiber Optics, Lasers And Optoelectronics',
    credits: 3,
    description: 'Introduction to fiber optics, lasers, and optoelectronic devices. Light propagation, optical fibers, and laser principles.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall'],
    level: 30000,
    careerTags: ['hardware', 'communications'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30500',
    name: 'Semiconductor Devices',
    credits: 3,
    description: 'Physics of semiconductor devices. PN junctions, diodes, BJTs, MOSFETs. Device characteristics and modeling.',
    prerequisites: ['ECE 25500', 'PHYS 27200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30600',
    name: 'Electronic Circuits And Systems Laboratory',
    credits: 1,
    description: 'Laboratory experiments in electronic circuits. Amplifier design, frequency response, and system integration.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['hardware'],
    interestTags: ['circuits', 'analog'],
    isMajorRequirement: false,
    isTechElective: false,
    isLabCredit: true,
    requirementCategory: null,
  },
  {
    code: 'ECE 30653',
    name: 'Introduction To Nanotechnology And Quantum Science',
    credits: 3,
    description: 'Introduction to nanotechnology and quantum science. Nanomaterials, quantum mechanics basics, and applications.',
    prerequisites: ['PHYS 27200'],
    corequisites: [],
    semesters: ['Fall'],
    level: 30000,
    careerTags: ['hardware'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30834',
    name: 'Fundamentals Of Computer Graphics',
    credits: 3,
    description: 'Computer graphics fundamentals. 2D/3D transformations, rendering, shading, and animation.',
    prerequisites: ['ECE 26400', 'MA 26500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['software'],
    interestTags: ['programming', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30862',
    name: 'Object-Oriented Programming In C++ And Java',
    credits: 3,
    description: 'Object-oriented programming using C++ and Java. Classes, inheritance, polymorphism, templates, and design patterns.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 31032',
    name: 'Power Systems Engineering',
    credits: 3,
    description: 'Introduction to power systems. Generation, transmission, distribution, and power system analysis.',
    prerequisites: ['ECE 20002'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 31000,
    careerTags: ['power'],
    interestTags: ['circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 31033',
    name: 'Power Electronics',
    credits: 3,
    description: 'Power semiconductor devices, DC-DC converters, DC-AC inverters, AC-DC rectifiers. PWM techniques and control.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 31000,
    careerTags: ['power', 'hardware'],
    interestTags: ['circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 33300',
    name: 'Automatic Control Systems',
    credits: 3,
    description: 'Analysis and design of automatic control systems. Transfer functions, stability, root locus, and frequency response.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 33000,
    careerTags: ['controls', 'robotics'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 33700',
    name: 'ASIC Design Laboratory',
    credits: 2,
    description: 'Application-specific integrated circuit design. VLSI design flow, synthesis, and verification.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 33000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital'],
    isMajorRequirement: false,
    isTechElective: true,
    isLabCredit: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 35100',
    name: 'Software Engineering',
    credits: 3,
    description: 'Software engineering principles and practices. Requirements, design, implementation, testing, and maintenance.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 35000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 35800',
    name: 'Introduction To VHDL',
    credits: 3,
    description: 'VHDL hardware description language. Syntax, simulation, and synthesis for digital design.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 35000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['digital', 'programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 36900',
    name: 'Discrete Mathematics For Computer Engineering',
    credits: 3,
    description: 'Logic, proof techniques, sets, relations, functions, algorithms, graphs, trees.',
    prerequisites: ['MA 16200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 36000,
    careerTags: ['software'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 38200',
    name: 'Feedback System Analysis And Design',
    credits: 3,
    description: 'Analysis and design of feedback control systems. Stability, root locus, frequency response, PID controllers.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 38000,
    careerTags: ['controls', 'robotics'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 38700',
    name: 'Electronics And System Engineering Through Robotics',
    credits: 3,
    description: 'Robotics fundamentals including sensors, actuators, control systems, and embedded programming.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 38000,
    careerTags: ['robotics', 'embedded'],
    interestTags: ['programming', 'circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  // ==================== 40000 LEVEL ====================
  {
    code: 'ECE 40400',
    name: 'Introduction To Computer Security',
    credits: 3,
    description: 'Computer security fundamentals. Cryptography, authentication, access control, and network security.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 40000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 40862',
    name: 'Software For Embedded Systems',
    credits: 3,
    description: 'Software development for embedded systems. Real-time programming, device drivers, and system integration.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 40000,
    careerTags: ['embedded', 'software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 41200',
    name: 'Introduction To Engineering Optics',
    credits: 3,
    description: 'Principles of optics. Wave optics, interference, diffraction, lasers, fiber optics.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall'],
    level: 41000,
    careerTags: ['hardware', 'communications'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 42500',
    name: 'Electric Machines',
    credits: 3,
    description: 'Principles of electric machines. DC machines, induction machines, synchronous machines.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 42000,
    careerTags: ['power'],
    interestTags: ['circuits', 'physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43200',
    name: 'Elements Of Power System Engineering',
    credits: 3,
    description: 'Power system modeling and analysis. Power flow, fault analysis, stability.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Fall'],
    level: 43000,
    careerTags: ['power'],
    interestTags: ['circuits', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43500',
    name: 'Object-Oriented Design Using C++ And Java',
    credits: 3,
    description: 'Advanced object-oriented design. Design patterns, frameworks, and software architecture.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 43000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43600',
    name: 'Digital Signal Processing',
    credits: 3,
    description: 'Digital signal processing. DFT, FFT, digital filter design, FIR and IIR filters.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 43000,
    careerTags: ['signals', 'ml'],
    interestTags: ['dsp', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 44200',
    name: 'Transmission Of Information',
    credits: 3,
    description: 'Information theory and communication systems. Source coding, channel coding, modulation.',
    prerequisites: ['ECE 30200', 'ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 44000,
    careerTags: ['communications', 'signals'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 44901',
    name: 'Machine Learning',
    credits: 3,
    description: 'Machine learning algorithms and applications. Supervised and unsupervised learning, neural networks.',
    prerequisites: ['ECE 30200', 'ECE 20875'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 44000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 45300',
    name: 'Fundamentals Of Nanoelectronics',
    credits: 3,
    description: 'Nanoelectronics fundamentals. Quantum mechanics, nanoscale devices, and emerging technologies.',
    prerequisites: ['ECE 30500'],
    corequisites: [],
    semesters: ['Fall'],
    level: 45000,
    careerTags: ['hardware'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 45500',
    name: 'Integrated Circuit Engineering',
    credits: 3,
    description: 'IC fabrication processes. Lithography, etching, deposition, and process integration.',
    prerequisites: ['ECE 30500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 45000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 45600',
    name: 'Digital Integrated Circuit Analysis And Design',
    credits: 3,
    description: 'Digital IC design. CMOS logic, layout, timing analysis, and low-power design.',
    prerequisites: ['ECE 27000', 'ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 45000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital', 'circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46500',
    name: 'Embedded Microprocessors',
    credits: 3,
    description: 'Embedded microprocessor systems. ARM architecture, peripherals, and real-time programming.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 46000,
    careerTags: ['embedded', 'software'],
    interestTags: ['programming', 'architecture'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46800',
    name: 'Introduction To Compilers And Translation Engineering',
    credits: 4,
    description: 'Compiler design. Lexical analysis, parsing, semantic analysis, code generation.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Spring'],
    level: 46000,
    careerTags: ['software'],
    interestTags: ['programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47200',
    name: 'Digital System Design VHDL',
    credits: 3,
    description: 'Digital system design using VHDL. Synthesis, simulation, and FPGA implementation.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['digital', 'programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47301',
    name: 'Introduction To Artificial Intelligence',
    credits: 3,
    description: 'AI fundamentals. Search, knowledge representation, planning, machine learning basics.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47400',
    name: 'Introduction To Radio Frequency Circuit Design',
    credits: 3,
    description: 'RF circuit design. Transmission lines, matching networks, amplifiers, and oscillators.',
    prerequisites: ['ECE 30411', 'ECE 25500'],
    corequisites: [],
    semesters: ['Fall'],
    level: 47000,
    careerTags: ['hardware', 'communications'],
    interestTags: ['circuits', 'analog'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47800',
    name: 'Robotics And Automation',
    credits: 3,
    description: 'Robotics fundamentals. Kinematics, dynamics, control, and path planning.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['robotics', 'controls'],
    interestTags: ['math', 'programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 48300',
    name: 'Digital Control Systems Analysis And Design',
    credits: 3,
    description: 'Digital control systems. Z-transform, discrete-time systems, digital controller design.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 48000,
    careerTags: ['controls', 'embedded'],
    interestTags: ['math', 'programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  // ==================== 50000+ LEVEL ====================
  {
    code: 'ECE 50201',
    name: 'Information Theory',
    credits: 3,
    description: 'Information theory. Entropy, mutual information, channel capacity, source coding.',
    prerequisites: ['ECE 30200'],
    corequisites: [],
    semesters: ['Fall'],
    level: 50000,
    careerTags: ['communications', 'ml'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 50863',
    name: 'Computer Network Systems',
    credits: 3,
    description: 'Advanced computer networks. Protocol design, performance analysis, wireless networks.',
    prerequisites: ['ECE 46300'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 50000,
    careerTags: ['communications', 'software'],
    interestTags: ['networking'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51018',
    name: 'Hybrid Electric Vehicles',
    credits: 3,
    description: 'Hybrid and electric vehicle technology. Powertrains, batteries, motors, and control systems.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Fall'],
    level: 51000,
    careerTags: ['power', 'controls'],
    interestTags: ['circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51214',
    name: 'CMOS Analog IC Design',
    credits: 3,
    description: 'CMOS analog circuit design. Amplifiers, current mirrors, bandgap references, data converters.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 51000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['analog', 'circuits'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51800',
    name: 'Digital Image Processing',
    credits: 3,
    description: 'Image processing. Enhancement, restoration, compression, segmentation, feature extraction.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 51000,
    careerTags: ['signals', 'ml'],
    interestTags: ['dsp', 'programming'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 52500',
    name: 'Introduction To Computer Graphics',
    credits: 3,
    description: 'Computer graphics. 3D rendering, shading, animation, and GPU programming.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 52000,
    careerTags: ['software'],
    interestTags: ['programming', 'math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 52900',
    name: 'Introduction To Microwave Engineering',
    credits: 3,
    description: 'Microwave engineering. Transmission lines, waveguides, microwave circuits, and antennas.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall'],
    level: 52000,
    careerTags: ['communications', 'hardware'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 53000',
    name: 'Wireless Communication Systems',
    credits: 3,
    description: 'Wireless communications. Channel modeling, modulation, multiple access, and cellular systems.',
    prerequisites: ['ECE 30200', 'ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 53000,
    careerTags: ['communications', 'signals'],
    interestTags: ['math'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 53100',
    name: 'Fiber Optic Communications',
    credits: 3,
    description: 'Fiber optic communication systems. Optical fibers, transmitters, receivers, and system design.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Spring'],
    level: 53000,
    careerTags: ['communications', 'hardware'],
    interestTags: ['physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 53202',
    name: 'Renewable Energy',
    credits: 3,
    description: 'Renewable energy systems. Solar, wind, and energy storage technologies.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Spring'],
    level: 53000,
    careerTags: ['power'],
    interestTags: ['circuits', 'physics'],
    isMajorRequirement: false,
    isTechElective: true,
    requirementCategory: 'depth',
  },
];
