import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface CourseData {
  code: string;
  name: string;
  credits: number;
  description: string;
  prerequisites: string[];
  corequisites: string[];
  semesters: string[];
  level: number;
  careerTags: string[];
  interestTags: string[];
  avgGPA: number;
  difficultyRating: number;
  workloadHours: number;
  // Professor data
  professors: string[];
  // Schedule info
  typicalDays: string[];
  hasMorningSection: boolean;
  hasAfternoonSection: boolean;
  hasEveningSection: boolean;
  hasFridayClass: boolean;
  hasOnlineOption: boolean;
  hasHybridOption: boolean;
  // Exam/Assignment intensity
  numExams: number;
  isProjectBased: boolean;
  isExamBased: boolean;
  homeworkIntensity: string;
  isCodingHeavy: boolean;
  isMathHeavy: boolean;
  examIntensity: string;
  hasGroupProjects: boolean;
  // Degree requirements
  isMajorRequirement: boolean;
  isTechElective: boolean;
  isGenEd: boolean;
  isLabCredit: boolean;
  requirementCategory: string | null;
}

// Complete ECE Course Dataset
const ECE_COURSES: CourseData[] = [
  // ==================== 20000 LEVEL (Sophomore) ====================
  {
    code: 'ECE 20000',
    name: 'Electrical And Computer Engineering Seminar',
    credits: 0,
    description: 'Introduction to ECE department, career paths, and academic planning. Required for all ECE students.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: [],
    interestTags: [],
    avgGPA: 4.0,
    difficultyRating: 1.0,
    workloadHours: 1,
    professors: [],
    typicalDays: ['W'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: false,
    isExamBased: false,
    homeworkIntensity: 'light',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20001',
    name: 'Electrical Engineering Fundamentals I',
    credits: 3,
    description: 'Introduction to electrical engineering concepts. Basic circuit elements, Kirchhoffs laws, nodal and mesh analysis, Thevenin and Norton equivalents, operational amplifiers, capacitors and inductors, first-order transient response.',
    prerequisites: ['PHYS 17200', 'MA 26100'],
    corequisites: ['ECE 20007'],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 20000,
    careerTags: ['hardware', 'embedded', 'signals'],
    interestTags: ['circuits', 'physics', 'analog'],
    avgGPA: 2.85,
    difficultyRating: 3.2,
    workloadHours: 12,
    professors: ['Mark Johnson', 'Shreyas Sen', 'Peter Bermel', 'Muhammad Hussain'],
    typicalDays: ['MWF', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20002',
    name: 'Electrical Engineering Fundamentals II',
    credits: 3,
    description: 'Second-order transient response, sinusoidal steady-state response, AC power analysis, frequency response, two-port networks, mutual inductance and transformers.',
    prerequisites: ['ECE 20001'],
    corequisites: ['ECE 20008'],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 20000,
    careerTags: ['hardware', 'signals', 'power'],
    interestTags: ['circuits', 'analog', 'physics'],
    avgGPA: 2.78,
    difficultyRating: 3.4,
    workloadHours: 13,
    professors: ['Mark Johnson', 'Shreyas Sen', 'Dimitrios Peroulis'],
    typicalDays: ['MWF', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20007',
    name: 'Electrical Engineering Fundamentals I Lab',
    credits: 1,
    description: 'Laboratory experiments in basic electrical circuits. Use of oscilloscopes, function generators, multimeters. Circuit construction and measurement techniques.',
    prerequisites: [],
    corequisites: ['ECE 20001'],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 20000,
    careerTags: ['hardware'],
    interestTags: ['circuits'],
    avgGPA: 3.45,
    difficultyRating: 2.0,
    workloadHours: 4,
    professors: [],
    typicalDays: ['MW', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: true,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20008',
    name: 'Electrical Engineering Fundamentals II Lab',
    credits: 1,
    description: 'Laboratory experiments in AC circuits, frequency response, and operational amplifiers. Advanced measurement and analysis techniques.',
    prerequisites: ['ECE 20007'],
    corequisites: ['ECE 20002'],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware', 'signals'],
    interestTags: ['circuits', 'analog'],
    avgGPA: 3.42,
    difficultyRating: 2.2,
    workloadHours: 4,
    professors: [],
    typicalDays: ['MW', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: true,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20100',
    name: 'Linear Circuit Analysis I',
    credits: 3,
    description: 'DC circuit analysis techniques including nodal analysis, mesh analysis, Thevenin and Norton equivalents, superposition. Introduction to first-order circuits.',
    prerequisites: ['PHYS 17200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware', 'power'],
    interestTags: ['circuits', 'physics'],
    avgGPA: 2.92,
    difficultyRating: 3.0,
    workloadHours: 11,
    professors: ['David Meyer', 'Byunghoo Jung'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20200',
    name: 'Linear Circuit Analysis II',
    credits: 3,
    description: 'AC circuit analysis, phasors, frequency response, Bode plots, Laplace transforms, transfer functions. Two-port network parameters.',
    prerequisites: ['ECE 20100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware', 'signals', 'power'],
    interestTags: ['circuits', 'analog'],
    avgGPA: 2.75,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['David Meyer', 'Kaushik Roy'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20869',
    name: 'Discrete Mathematics for Computer Engineering',
    credits: 3,
    description: 'Logic, proof techniques, sets, relations, functions, algorithms, graphs, trees. Mathematical foundations for computer engineering.',
    prerequisites: ['MA 16200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['software', 'hardware'],
    interestTags: ['math', 'programming'],
    avgGPA: 2.95,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: ['Saurabh Bagchi', 'Cheng-Kok Koh'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 20875',
    name: 'Python for Data Science',
    credits: 3,
    description: 'Introduction to Python programming with applications in data analysis. NumPy, Pandas, Matplotlib, basic statistics, and machine learning concepts.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 20000,
    careerTags: ['software', 'ml'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.25,
    difficultyRating: 2.5,
    workloadHours: 10,
    professors: ['David Inouye', 'Qiang Qiu', 'Stanley Chan'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 25500',
    name: 'Introduction to Electronic Analysis and Design',
    credits: 3,
    description: 'Electronic device characteristics. Diode and transistor circuits. Amplifier analysis and design. Frequency response of amplifiers.',
    prerequisites: ['ECE 20002'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 25000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['analog', 'circuits'],
    avgGPA: 2.68,
    difficultyRating: 3.8,
    workloadHours: 14,
    professors: ['Byunghoo Jung', 'Mark Bell'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 26400',
    name: 'Advanced C Programming',
    credits: 3,
    description: 'Advanced C programming concepts including pointers, dynamic memory allocation, data structures, file I/O, and system programming.',
    prerequisites: ['CS 15900'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 26000,
    careerTags: ['software', 'embedded'],
    interestTags: ['programming'],
    avgGPA: 2.92,
    difficultyRating: 3.5,
    workloadHours: 14,
    professors: ['Yung-Hsiang Lu', 'Cheng-Kok Koh', 'James Krogmeier'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 27000',
    name: 'Introduction to Digital System Design',
    credits: 4,
    description: 'Digital logic design fundamentals. Combinational and sequential circuit design. Boolean algebra, Karnaugh maps, flip-flops, state machines. FPGA implementation.',
    prerequisites: ['ECE 20001'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 27000,
    careerTags: ['hardware', 'embedded', 'vlsi'],
    interestTags: ['digital', 'circuits'],
    avgGPA: 2.65,
    difficultyRating: 3.8,
    workloadHours: 16,
    professors: ['Cheng-Kok Koh', 'Anand Raghunathan', 'Mark Johnson'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'high',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 29401',
    name: 'ECE Sophomore Seminar',
    credits: 1,
    description: 'Professional development, career planning, and introduction to ECE research and industry opportunities.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 29000,
    careerTags: [],
    interestTags: [],
    avgGPA: 3.85,
    difficultyRating: 1.2,
    workloadHours: 2,
    professors: [],
    typicalDays: ['W'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: false,
    isExamBased: false,
    homeworkIntensity: 'light',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },

  // ==================== 30000 LEVEL (Junior) ====================
  {
    code: 'ECE 30100',
    name: 'Signals and Systems',
    credits: 3,
    description: 'Continuous and discrete-time signals and systems. Convolution, Fourier series, Fourier transform, Laplace transform, Z-transform. Sampling and aliasing.',
    prerequisites: ['ECE 20002', 'MA 26600'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 30000,
    careerTags: ['signals', 'communications', 'ml', 'controls'],
    interestTags: ['math', 'dsp'],
    avgGPA: 2.58,
    difficultyRating: 4.2,
    workloadHours: 15,
    professors: ['Mireille Boutin', 'Charlie Bouman', 'Stanley Chan'],
    typicalDays: ['MWF', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 30200',
    name: 'Probabilistic Methods in Electrical and Computer Engineering',
    credits: 3,
    description: 'Probability theory, random variables, probability distributions, expectation, random processes. Applications in communications, signal processing, and machine learning.',
    prerequisites: ['MA 26500'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 30000,
    careerTags: ['signals', 'communications', 'ml'],
    interestTags: ['math'],
    avgGPA: 2.72,
    difficultyRating: 3.8,
    workloadHours: 14,
    professors: ['Mark Bell', 'Xiaojun Lin', 'David Love'],
    typicalDays: ['MWF', 'TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 30411',
    name: 'Electromagnetics I',
    credits: 3,
    description: 'Electrostatics, magnetostatics, Maxwell equations, time-varying fields, plane waves. Introduction to transmission lines.',
    prerequisites: ['ECE 20002', 'MA 26200', 'PHYS 27200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['hardware', 'communications', 'power'],
    interestTags: ['physics'],
    avgGPA: 2.45,
    difficultyRating: 4.5,
    workloadHours: 16,
    professors: ['Dan Jiao', 'Peter Bermel', 'Minghao Qi'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 30412',
    name: 'Electromagnetics II',
    credits: 3,
    description: 'Transmission lines, waveguides, antennas, radiation, propagation. Microwave circuit concepts.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['communications', 'hardware'],
    interestTags: ['physics'],
    avgGPA: 2.52,
    difficultyRating: 4.3,
    workloadHours: 15,
    professors: ['Dan Jiao', 'Dimitrios Peroulis'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 31100',
    name: 'Electric and Magnetic Fields',
    credits: 3,
    description: 'Electric and magnetic field theory with engineering applications. Coulombs law, Gausss law, electric potential, magnetic fields, Faradays law.',
    prerequisites: ['PHYS 27200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 31000,
    careerTags: ['power', 'hardware'],
    interestTags: ['physics'],
    avgGPA: 2.65,
    difficultyRating: 3.8,
    workloadHours: 13,
    professors: ['Peter Bermel', 'Various Faculty'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 32100',
    name: 'Electromechanical Motion Devices',
    credits: 3,
    description: 'Principles of electromechanical energy conversion. DC machines, transformers, induction machines, synchronous machines.',
    prerequisites: ['ECE 20002'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 32000,
    careerTags: ['power', 'controls', 'robotics'],
    interestTags: ['physics', 'circuits'],
    avgGPA: 2.78,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['Steven Pekarek', 'Scott Sudhoff'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 33200',
    name: 'Power Electronics',
    credits: 3,
    description: 'Power semiconductor devices, DC-DC converters, DC-AC inverters, AC-DC rectifiers. PWM techniques and control.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 33000,
    careerTags: ['power', 'hardware'],
    interestTags: ['circuits', 'analog'],
    avgGPA: 2.82,
    difficultyRating: 3.6,
    workloadHours: 13,
    professors: ['Steven Pekarek', 'Dionysios Aliprantis'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 36200',
    name: 'Microprocessor Systems and Interfacing',
    credits: 4,
    description: 'Microprocessor architecture, assembly language programming, hardware interfacing. Interrupts, timers, serial communication, A/D and D/A conversion.',
    prerequisites: ['ECE 27000', 'ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 36000,
    careerTags: ['embedded', 'hardware', 'software'],
    interestTags: ['architecture', 'programming', 'digital'],
    avgGPA: 2.88,
    difficultyRating: 3.6,
    workloadHours: 15,
    professors: ['James Krogmeier', 'Mark Johnson', 'Cheng-Kok Koh'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 36400',
    name: 'Software Engineering Tools Lab',
    credits: 1,
    description: 'Practical software engineering tools and practices. Version control, debugging, testing frameworks, build systems.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 36000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 3.35,
    difficultyRating: 2.2,
    workloadHours: 4,
    professors: ['Yung-Hsiang Lu'],
    typicalDays: ['W'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: true,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 36800',
    name: 'Data Structures',
    credits: 3,
    description: 'Fundamental data structures: arrays, linked lists, stacks, queues, trees, graphs. Sorting and searching algorithms. Algorithm complexity analysis.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring', 'Summer'],
    level: 36000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 2.95,
    difficultyRating: 3.4,
    workloadHours: 12,
    professors: ['Yung-Hsiang Lu', 'Saurabh Bagchi'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'core',
  },
  {
    code: 'ECE 37100',
    name: 'Feedback Control Systems',
    credits: 3,
    description: 'Analysis and design of feedback control systems. Stability, root locus, frequency response methods, PID controllers.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 37000,
    careerTags: ['controls', 'robotics', 'power'],
    interestTags: ['math'],
    avgGPA: 2.62,
    difficultyRating: 4.0,
    workloadHours: 14,
    professors: ['Shreyas Sundaram', 'Jianghai Hu'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 38200',
    name: 'Semiconductor Devices',
    credits: 3,
    description: 'Physics of semiconductor devices. PN junctions, diodes, BJTs, MOSFETs. Device characteristics and modeling.',
    prerequisites: ['ECE 25500', 'PHYS 27200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 38000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['physics', 'analog'],
    avgGPA: 2.55,
    difficultyRating: 4.2,
    workloadHours: 15,
    professors: ['Mark Lundstrom', 'Gerhard Klimeck', 'Muhammad Hussain'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },

  // ==================== 40000 LEVEL (Senior) ====================
  {
    code: 'ECE 40400',
    name: 'Introduction to Digital Signal Processing',
    credits: 3,
    description: 'Discrete-time signal processing. DFT, FFT, digital filter design. FIR and IIR filters. Applications in audio, image, and communication systems.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 40000,
    careerTags: ['signals', 'ml', 'communications'],
    interestTags: ['dsp', 'math', 'programming'],
    avgGPA: 2.98,
    difficultyRating: 3.8,
    workloadHours: 14,
    professors: ['Charlie Bouman', 'Mireille Boutin'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 40862',
    name: 'Introduction to Artificial Intelligence',
    credits: 3,
    description: 'Fundamentals of AI including search, knowledge representation, planning, machine learning basics, and neural networks.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 40000,
    careerTags: ['ml', 'software', 'robotics'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.12,
    difficultyRating: 3.4,
    workloadHours: 12,
    professors: ['Qiang Qiu', 'Eugenio Culurciello'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 41200',
    name: 'Optics and Photonics',
    credits: 3,
    description: 'Principles of optics and photonics. Wave optics, interference, diffraction, lasers, fiber optics, optical devices.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall'],
    level: 41000,
    careerTags: ['hardware', 'communications'],
    interestTags: ['physics'],
    avgGPA: 2.88,
    difficultyRating: 3.6,
    workloadHours: 12,
    professors: ['Andrew Weiner', 'Minghao Qi'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43700',
    name: 'Introduction to VLSI Design',
    credits: 3,
    description: 'VLSI design methodology. CMOS logic, layout, simulation, verification. Introduction to chip design flow.',
    prerequisites: ['ECE 27000', 'ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 43000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital', 'circuits'],
    avgGPA: 2.82,
    difficultyRating: 3.9,
    workloadHours: 14,
    professors: ['Kaushik Roy', 'Anand Raghunathan'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43800',
    name: 'Analog VLSI',
    credits: 3,
    description: 'Analog integrated circuit design. Operational amplifiers, current mirrors, bandgap references, data converters.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Spring'],
    level: 43000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['analog', 'circuits'],
    avgGPA: 2.72,
    difficultyRating: 4.1,
    workloadHours: 14,
    professors: ['Byunghoo Jung', 'Saeed Mohammadi'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 44300',
    name: 'Power System Analysis',
    credits: 3,
    description: 'Power system modeling and analysis. Power flow, fault analysis, stability, economic dispatch.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Fall'],
    level: 44000,
    careerTags: ['power'],
    interestTags: ['circuits', 'math'],
    avgGPA: 2.85,
    difficultyRating: 3.6,
    workloadHours: 12,
    professors: ['Dionysios Aliprantis', 'Steven Pekarek'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 45400',
    name: 'Digital Communications',
    credits: 3,
    description: 'Digital communication systems. Modulation, detection, channel coding. Performance analysis in AWGN and fading channels.',
    prerequisites: ['ECE 30200', 'ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 45000,
    careerTags: ['communications', 'signals'],
    interestTags: ['math', 'dsp'],
    avgGPA: 2.68,
    difficultyRating: 4.0,
    workloadHours: 14,
    professors: ['David Love', 'James Krogmeier'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 3,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46100',
    name: 'Software Engineering',
    credits: 3,
    description: 'Software engineering principles. Requirements, design, implementation, testing, maintenance. Agile methodologies.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 46000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 3.15,
    difficultyRating: 2.8,
    workloadHours: 10,
    professors: ['James Davis', 'Lin Tan'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46300',
    name: 'Introduction to Computer Communication Networks',
    credits: 3,
    description: 'Computer networking fundamentals. OSI model, TCP/IP, routing, congestion control, network applications.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 46000,
    careerTags: ['communications', 'software'],
    interestTags: ['networking', 'programming'],
    avgGPA: 3.02,
    difficultyRating: 3.3,
    workloadHours: 11,
    professors: ['Sanjay Rao', 'Y. Charlie Hu'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46900',
    name: 'Operating Systems Engineering',
    credits: 3,
    description: 'Operating system design and implementation. Processes, threads, memory management, file systems, security.',
    prerequisites: ['ECE 36800', 'ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 46000,
    careerTags: ['software', 'embedded'],
    interestTags: ['programming', 'os'],
    avgGPA: 2.75,
    difficultyRating: 4.0,
    workloadHours: 15,
    professors: ['Y. Charlie Hu', 'Dongyan Xu'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47300',
    name: 'Computer Architecture',
    credits: 3,
    description: 'Advanced computer architecture. Pipelining, caches, virtual memory, multiprocessors, GPU architecture.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['hardware', 'embedded', 'software'],
    interestTags: ['architecture', 'digital'],
    avgGPA: 2.85,
    difficultyRating: 3.7,
    workloadHours: 13,
    professors: ['Mithuna Thottethodi', 'T. N. Vijaykumar'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47700',
    name: 'Digital Systems Senior Project',
    credits: 3,
    description: 'Capstone design project in digital systems. Team-based design, implementation, and testing of a complete system.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['embedded', 'hardware', 'software'],
    interestTags: ['digital', 'programming'],
    avgGPA: 3.35,
    difficultyRating: 3.0,
    workloadHours: 12,
    professors: ['Mark Johnson', 'Various Faculty'],
    typicalDays: ['TR'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'capstone',
  },
  {
    code: 'ECE 49022',
    name: 'Senior Design Project I',
    credits: 2,
    description: 'First semester of capstone senior design. Project proposal, design reviews, team formation.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall'],
    level: 49000,
    careerTags: [],
    interestTags: [],
    avgGPA: 3.25,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: true,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'capstone',
  },
  {
    code: 'ECE 49023',
    name: 'Senior Design Project II',
    credits: 3,
    description: 'Second semester of capstone senior design. Project implementation, testing, and final demonstration.',
    prerequisites: ['ECE 49022'],
    corequisites: [],
    semesters: ['Spring'],
    level: 49000,
    careerTags: [],
    interestTags: [],
    avgGPA: 3.30,
    difficultyRating: 3.5,
    workloadHours: 15,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: true,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: true,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'capstone',
  },
  {
    code: 'ECE 49500',
    name: 'Introduction to Machine Learning',
    credits: 3,
    description: 'Fundamentals of machine learning. Supervised and unsupervised learning, neural networks, deep learning basics.',
    prerequisites: ['ECE 30200', 'ECE 20875'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 49000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.08,
    difficultyRating: 3.5,
    workloadHours: 13,
    professors: ['Stanley Chan', 'David Inouye', 'Qiang Qiu'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },

  // ==================== 50000+ LEVEL (Graduate) ====================
  {
    code: 'ECE 50024',
    name: 'Machine Learning',
    credits: 3,
    description: 'Graduate-level machine learning. Statistical learning theory, SVMs, kernel methods, ensemble methods, deep learning.',
    prerequisites: ['ECE 49500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 50000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.15,
    difficultyRating: 4.0,
    workloadHours: 16,
    professors: ['David Inouye', 'Bruno Ribeiro'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 50863',
    name: 'Deep Learning',
    credits: 3,
    description: 'Advanced deep learning. CNNs, RNNs, transformers, GANs. Applications in computer vision and NLP.',
    prerequisites: ['ECE 49500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 50000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.22,
    difficultyRating: 3.6,
    workloadHours: 14,
    professors: ['Qiang Qiu', 'Eugenio Culurciello'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 1,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 55900',
    name: 'Microprocessor Architectures',
    credits: 3,
    description: 'Advanced computer architecture. Superscalar processors, out-of-order execution, speculation, multi-threading.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall'],
    level: 55000,
    careerTags: ['hardware', 'embedded', 'software'],
    interestTags: ['architecture', 'digital'],
    avgGPA: 2.92,
    difficultyRating: 3.7,
    workloadHours: 13,
    professors: ['T. N. Vijaykumar', 'Mithuna Thottethodi'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 56500',
    name: 'Computer Communication Networks',
    credits: 3,
    description: 'Advanced networking. Network protocols, performance analysis, wireless networks, network security.',
    prerequisites: ['ECE 30200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 56000,
    careerTags: ['communications', 'software'],
    interestTags: ['networking'],
    avgGPA: 3.05,
    difficultyRating: 3.3,
    workloadHours: 11,
    professors: ['Sanjay Rao', 'Xiaojun Lin'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 57000',
    name: 'Artificial Intelligence',
    credits: 3,
    description: 'Advanced AI topics. Search algorithms, game playing, constraint satisfaction, probabilistic reasoning, planning.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall'],
    level: 57000,
    careerTags: ['ml', 'software', 'robotics'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.10,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['Qiang Qiu'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 57300',
    name: 'Compilers and Translator Writing Systems',
    credits: 3,
    description: 'Compiler design and implementation. Lexical analysis, parsing, semantic analysis, code generation, optimization.',
    prerequisites: ['ECE 36800', 'ECE 46900'],
    corequisites: [],
    semesters: ['Spring'],
    level: 57000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 2.95,
    difficultyRating: 4.0,
    workloadHours: 15,
    professors: ['Milind Kulkarni', 'Xiaokang Qiu'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 58000',
    name: 'Optimization Methods for Systems and Control',
    credits: 3,
    description: 'Optimization techniques for control systems. Convex optimization, linear programming, dynamic programming.',
    prerequisites: ['MA 26500'],
    corequisites: [],
    semesters: ['Fall'],
    level: 58000,
    careerTags: ['controls', 'robotics', 'ml'],
    interestTags: ['math'],
    avgGPA: 2.85,
    difficultyRating: 4.2,
    workloadHours: 14,
    professors: ['Shreyas Sundaram', 'Jianghai Hu'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 58500',
    name: 'Digital Image Processing',
    credits: 3,
    description: 'Image processing fundamentals. Image enhancement, restoration, compression, segmentation, feature extraction.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 58000,
    careerTags: ['signals', 'ml'],
    interestTags: ['dsp', 'programming'],
    avgGPA: 3.18,
    difficultyRating: 3.4,
    workloadHours: 12,
    professors: ['Charlie Bouman', 'Stanley Chan'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 59500',
    name: 'Computer Vision',
    credits: 3,
    description: 'Computer vision algorithms. Image formation, feature detection, object recognition, 3D reconstruction.',
    prerequisites: ['ECE 30100', 'ECE 30200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 59000,
    careerTags: ['ml', 'robotics'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.10,
    difficultyRating: 3.6,
    workloadHours: 13,
    professors: ['Stanley Chan', 'Qiang Qiu'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 60000',
    name: 'Random Variables and Signals',
    credits: 3,
    description: 'Advanced probability theory. Random processes, spectral analysis, estimation theory.',
    prerequisites: ['ECE 30200'],
    corequisites: [],
    semesters: ['Fall'],
    level: 60000,
    careerTags: ['signals', 'communications', 'ml'],
    interestTags: ['math'],
    avgGPA: 2.88,
    difficultyRating: 4.3,
    workloadHours: 15,
    professors: ['Mark Bell', 'David Love'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 60100',
    name: 'Analysis of Linear Systems',
    credits: 3,
    description: 'Graduate-level linear systems theory. State-space methods, controllability, observability, stability.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall'],
    level: 60000,
    careerTags: ['controls', 'signals'],
    interestTags: ['math'],
    avgGPA: 2.82,
    difficultyRating: 4.4,
    workloadHours: 16,
    professors: ['Shreyas Sundaram'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 60872',
    name: 'Fault-Tolerant Computer System Design',
    credits: 3,
    description: 'Design of reliable computing systems. Redundancy, error detection and correction, system reliability.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Spring'],
    level: 60000,
    careerTags: ['hardware', 'software', 'embedded'],
    interestTags: ['architecture', 'digital'],
    avgGPA: 3.05,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['Saurabh Bagchi'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 64300',
    name: 'Parallel Processing',
    credits: 3,
    description: 'Parallel computing architectures and programming. Shared memory, message passing, GPUs, parallel algorithms.',
    prerequisites: ['ECE 47300'],
    corequisites: [],
    semesters: ['Spring'],
    level: 64000,
    careerTags: ['software', 'hardware'],
    interestTags: ['programming', 'architecture'],
    avgGPA: 3.00,
    difficultyRating: 3.7,
    workloadHours: 13,
    professors: ['Milind Kulkarni'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 69500',
    name: 'Advanced Topics in ECE',
    credits: 3,
    description: 'Special topics in electrical and computer engineering. Content varies by semester.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 69000,
    careerTags: [],
    interestTags: [],
    avgGPA: 3.25,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: true,
    hasHybridOption: true,
    numExams: 1,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'breadth',
  },
  // ==================== ADDITIONAL COURSES ====================
  {
    code: 'ECE 15200',
    name: 'Programming For Engineers',
    credits: 3,
    description: 'Introduction to programming concepts for engineering students. Problem solving, algorithms, and basic data structures using Python.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 15000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 3.1,
    difficultyRating: 2.5,
    workloadHours: 8,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: null,
  },
  {
    code: 'ECE 20700',
    name: 'Electronic Measurement Techniques',
    credits: 1,
    description: 'Laboratory techniques for electronic measurements. Oscilloscopes, multimeters, signal generators, and data acquisition.',
    prerequisites: [],
    corequisites: ['ECE 20001'],
    semesters: ['Fall', 'Spring'],
    level: 20000,
    careerTags: ['hardware'],
    interestTags: ['circuits'],
    avgGPA: 3.4,
    difficultyRating: 2.0,
    workloadHours: 3,
    professors: [],
    typicalDays: ['T', 'R'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'light',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: null,
  },
  {
    code: 'ECE 22900',
    name: 'C Programming For ECE',
    credits: 3,
    description: 'Introduction to C programming for ECE students. Variables, control structures, functions, pointers, and basic data structures.',
    prerequisites: [],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 22000,
    careerTags: ['software', 'embedded'],
    interestTags: ['programming'],
    avgGPA: 3.0,
    difficultyRating: 2.8,
    workloadHours: 10,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 30010',
    name: 'Intro To Machine Learning And Pattern Recognition',
    credits: 3,
    description: 'Fundamentals of machine learning and pattern recognition. Classification, regression, clustering, and neural networks.',
    prerequisites: ['ECE 30200', 'ECE 20875'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.15,
    difficultyRating: 3.5,
    workloadHours: 14,
    professors: ['Mireille Boutin', 'Stanley Chan'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30414',
    name: 'Elements Of Fiber Optics, Lasers And Optoelectronics',
    credits: 3,
    description: 'Introduction to fiber optics, lasers, and optoelectronic devices. Light propagation, optical fibers, and laser principles.',
    prerequisites: ['ECE 30411'],
    corequisites: [],
    semesters: ['Fall'],
    level: 30000,
    careerTags: ['hardware', 'communications'],
    interestTags: ['physics'],
    avgGPA: 3.2,
    difficultyRating: 3.3,
    workloadHours: 10,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30500',
    name: 'Semiconductor Devices',
    credits: 3,
    description: 'Physics of semiconductor devices. PN junctions, diodes, BJTs, MOSFETs. Device characteristics and modeling.',
    prerequisites: ['ECE 25500', 'PHYS 27200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['physics'],
    avgGPA: 2.95,
    difficultyRating: 3.8,
    workloadHours: 12,
    professors: ['Muhammad Ashraful Alam', 'Peide Ye'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30600',
    name: 'Electronic Circuits And Systems Laboratory',
    credits: 1,
    description: 'Laboratory experiments in electronic circuits. Amplifier design, frequency response, and system integration.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['hardware'],
    interestTags: ['circuits', 'analog'],
    avgGPA: 3.3,
    difficultyRating: 2.5,
    workloadHours: 4,
    professors: [],
    typicalDays: ['T', 'W', 'R'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: true,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: false,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: null,
  },
  {
    code: 'ECE 30834',
    name: 'Fundamentals Of Computer Graphics',
    credits: 3,
    description: 'Computer graphics fundamentals. 2D/3D transformations, rendering, shading, and animation.',
    prerequisites: ['ECE 26400', 'MA 26500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.1,
    difficultyRating: 3.2,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 30862',
    name: 'Object-Oriented Programming In C++ And Java',
    credits: 3,
    description: 'Object-oriented programming using C++ and Java. Classes, inheritance, polymorphism, templates, and design patterns.',
    prerequisites: ['ECE 26400'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 30000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 3.05,
    difficultyRating: 3.0,
    workloadHours: 12,
    professors: ['Aravind Machiry'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'breadth',
  },
  {
    code: 'ECE 31032',
    name: 'Power Systems Engineering',
    credits: 3,
    description: 'Introduction to power systems. Generation, transmission, distribution, and power system analysis.',
    prerequisites: ['ECE 20002'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 31000,
    careerTags: ['power'],
    interestTags: ['circuits'],
    avgGPA: 3.0,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: ['Dionysios Aliprantis'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 33300',
    name: 'Automatic Control Systems',
    credits: 3,
    description: 'Analysis and design of automatic control systems. Transfer functions, stability, root locus, and frequency response.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 33000,
    careerTags: ['controls', 'robotics'],
    interestTags: ['math'],
    avgGPA: 2.9,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 33700',
    name: 'ASIC Design Laboratory',
    credits: 2,
    description: 'Application-specific integrated circuit design. VLSI design flow, synthesis, and verification.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 33000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital'],
    avgGPA: 3.2,
    difficultyRating: 3.0,
    workloadHours: 8,
    professors: [],
    typicalDays: ['T', 'R'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 0,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: true,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 35800',
    name: 'Introduction To VHDL',
    credits: 3,
    description: 'VHDL hardware description language. Syntax, simulation, and synthesis for digital design.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 35000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['digital', 'programming'],
    avgGPA: 3.1,
    difficultyRating: 3.0,
    workloadHours: 10,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 38200',
    name: 'Feedback System Analysis And Design',
    credits: 3,
    description: 'Analysis and design of feedback control systems. Stability, root locus, frequency response, PID controllers.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 38000,
    careerTags: ['controls', 'robotics'],
    interestTags: ['math'],
    avgGPA: 2.95,
    difficultyRating: 3.6,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 38700',
    name: 'Electronics And System Engineering Through Robotics',
    credits: 3,
    description: 'Robotics fundamentals including sensors, actuators, control systems, and embedded programming.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 38000,
    careerTags: ['robotics', 'embedded'],
    interestTags: ['programming', 'circuits'],
    avgGPA: 3.3,
    difficultyRating: 3.0,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 1,
    isProjectBased: true,
    isExamBased: false,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'low',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 40400',
    name: 'Introduction To Computer Security',
    credits: 3,
    description: 'Computer security fundamentals. Cryptography, authentication, access control, and network security.',
    prerequisites: ['ECE 36800'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 40000,
    careerTags: ['software'],
    interestTags: ['programming'],
    avgGPA: 3.2,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: ['Aravind Machiry', 'Antonio Bianchi'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 43600',
    name: 'Digital Signal Processing',
    credits: 3,
    description: 'Digital signal processing. DFT, FFT, digital filter design, FIR and IIR filters.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 43000,
    careerTags: ['signals', 'ml'],
    interestTags: ['dsp', 'math'],
    avgGPA: 2.9,
    difficultyRating: 3.8,
    workloadHours: 14,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 44901',
    name: 'Machine Learning',
    credits: 3,
    description: 'Machine learning algorithms and applications. Supervised and unsupervised learning, neural networks, deep learning.',
    prerequisites: ['ECE 30200', 'ECE 20875'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 44000,
    careerTags: ['ml', 'software'],
    interestTags: ['programming', 'math'],
    avgGPA: 3.1,
    difficultyRating: 3.5,
    workloadHours: 14,
    professors: ['Qiang Qiu', 'Mireille Boutin'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 45600',
    name: 'Digital Integrated Circuit Analysis And Design',
    credits: 3,
    description: 'Digital IC design. CMOS logic, layout, timing analysis, and low-power design.',
    prerequisites: ['ECE 27000', 'ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 45000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['digital', 'circuits'],
    avgGPA: 2.85,
    difficultyRating: 4.0,
    workloadHours: 14,
    professors: ['Kaushik Roy'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 46500',
    name: 'Embedded Microprocessors',
    credits: 3,
    description: 'Embedded microprocessor systems. ARM architecture, peripherals, and real-time programming.',
    prerequisites: ['ECE 36200'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 46000,
    careerTags: ['embedded', 'software'],
    interestTags: ['programming', 'architecture'],
    avgGPA: 3.1,
    difficultyRating: 3.3,
    workloadHours: 12,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47200',
    name: 'Digital System Design With VHDL',
    credits: 3,
    description: 'Digital system design using VHDL. Synthesis, simulation, and FPGA implementation.',
    prerequisites: ['ECE 27000'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['hardware', 'vlsi'],
    interestTags: ['digital', 'programming'],
    avgGPA: 3.05,
    difficultyRating: 3.2,
    workloadHours: 12,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: false,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: false,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 47800',
    name: 'Robotics And Automation',
    credits: 3,
    description: 'Robotics fundamentals. Kinematics, dynamics, control, and path planning.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 47000,
    careerTags: ['robotics', 'controls'],
    interestTags: ['math', 'programming'],
    avgGPA: 3.15,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['Byung-Cheol Min'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 48300',
    name: 'Digital Control Systems',
    credits: 3,
    description: 'Digital control systems. Z-transform, discrete-time systems, digital controller design.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 48000,
    careerTags: ['controls', 'embedded'],
    interestTags: ['math', 'programming'],
    avgGPA: 2.9,
    difficultyRating: 3.8,
    workloadHours: 12,
    professors: [],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51018',
    name: 'Hybrid Electric Vehicles',
    credits: 3,
    description: 'Hybrid and electric vehicle technology. Powertrains, batteries, motors, and control systems.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Fall'],
    level: 51000,
    careerTags: ['power', 'controls'],
    interestTags: ['circuits'],
    avgGPA: 3.3,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: ['Scott Sudhoff'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51214',
    name: 'CMOS Analog IC Design',
    credits: 3,
    description: 'CMOS analog circuit design. Amplifiers, current mirrors, bandgap references, data converters.',
    prerequisites: ['ECE 25500'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 51000,
    careerTags: ['vlsi', 'hardware'],
    interestTags: ['analog', 'circuits'],
    avgGPA: 2.85,
    difficultyRating: 4.0,
    workloadHours: 14,
    professors: ['Byunghoo Jung'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 51800',
    name: 'Digital Image Processing',
    credits: 3,
    description: 'Image processing. Enhancement, restoration, compression, segmentation, feature extraction.',
    prerequisites: ['ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 51000,
    careerTags: ['signals', 'ml'],
    interestTags: ['dsp', 'programming'],
    avgGPA: 3.1,
    difficultyRating: 3.5,
    workloadHours: 12,
    professors: ['Edward Delp', 'Jan Allebach'],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: true,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: true,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 53000',
    name: 'Wireless Communication Systems',
    credits: 3,
    description: 'Wireless communications. Channel modeling, modulation, multiple access, and cellular systems.',
    prerequisites: ['ECE 30200', 'ECE 30100'],
    corequisites: [],
    semesters: ['Fall', 'Spring'],
    level: 53000,
    careerTags: ['communications', 'signals'],
    interestTags: ['math'],
    avgGPA: 3.0,
    difficultyRating: 3.8,
    workloadHours: 12,
    professors: ['David Love', 'James Krogmeier'],
    typicalDays: ['MWF'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: true,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: false,
    isExamBased: true,
    homeworkIntensity: 'heavy',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'high',
    hasGroupProjects: false,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
  {
    code: 'ECE 53202',
    name: 'Renewable Energy',
    credits: 3,
    description: 'Renewable energy systems. Solar, wind, and energy storage technologies.',
    prerequisites: ['ECE 32100'],
    corequisites: [],
    semesters: ['Spring'],
    level: 53000,
    careerTags: ['power'],
    interestTags: ['circuits', 'physics'],
    avgGPA: 3.25,
    difficultyRating: 3.2,
    workloadHours: 10,
    professors: [],
    typicalDays: ['TR'],
    hasMorningSection: true,
    hasAfternoonSection: false,
    hasEveningSection: false,
    hasFridayClass: false,
    hasOnlineOption: false,
    hasHybridOption: false,
    numExams: 2,
    isProjectBased: true,
    isExamBased: true,
    homeworkIntensity: 'moderate',
    isCodingHeavy: false,
    isMathHeavy: true,
    examIntensity: 'medium',
    hasGroupProjects: true,
    isMajorRequirement: false,
    isTechElective: true,
    isGenEd: false,
    isLabCredit: false,
    requirementCategory: 'depth',
  },
];

function generateGradeDistribution(avgGPA: number): { A: number; B: number; C: number; D: number; F: number } {
  const base = avgGPA / 4;
  return {
    A: Math.round(base * 35 + Math.random() * 10),
    B: Math.round(30 + Math.random() * 10),
    C: Math.round((1 - base) * 25 + Math.random() * 10),
    D: Math.round((1 - base) * 15 + Math.random() * 5),
    F: Math.round((1 - base) * 8 + Math.random() * 3),
  };
}

async function seed() {
  console.log('Seeding database with comprehensive ECE course data...\n');

  let seededCount = 0;

  for (const course of ECE_COURSES) {
    try {
      await prisma.course.upsert({
        where: { code: course.code },
        update: {
          name: course.name,
          credits: course.credits,
          description: course.description,
          prerequisites: course.prerequisites,
          corequisites: course.corequisites,
          semesters: course.semesters,
          level: course.level,
          careerTags: course.careerTags,
          interestTags: course.interestTags,
          avgGPA: course.avgGPA,
          difficultyRating: course.difficultyRating,
          workloadHours: course.workloadHours,
          gradeDistribution: generateGradeDistribution(course.avgGPA),
          // New fields
          professors: course.professors,
          typicalDays: course.typicalDays,
          hasMorningSection: course.hasMorningSection,
          hasAfternoonSection: course.hasAfternoonSection,
          hasEveningSection: course.hasEveningSection,
          hasFridayClass: course.hasFridayClass,
          hasOnlineOption: course.hasOnlineOption,
          hasHybridOption: course.hasHybridOption,
          numExams: course.numExams,
          isProjectBased: course.isProjectBased,
          isExamBased: course.isExamBased,
          homeworkIntensity: course.homeworkIntensity,
          isCodingHeavy: course.isCodingHeavy,
          isMathHeavy: course.isMathHeavy,
          examIntensity: course.examIntensity,
          hasGroupProjects: course.hasGroupProjects,
          isMajorRequirement: course.isMajorRequirement,
          isTechElective: course.isTechElective,
          isGenEd: course.isGenEd,
          isLabCredit: course.isLabCredit,
          requirementCategory: course.requirementCategory,
        },
        create: {
          code: course.code,
          name: course.name,
          credits: course.credits,
          description: course.description,
          prerequisites: course.prerequisites,
          corequisites: course.corequisites,
          semesters: course.semesters,
          department: 'ECE',
          level: course.level,
          careerTags: course.careerTags,
          interestTags: course.interestTags,
          avgGPA: course.avgGPA,
          difficultyRating: course.difficultyRating,
          workloadHours: course.workloadHours,
          gradeDistribution: generateGradeDistribution(course.avgGPA),
          // New fields
          professors: course.professors,
          typicalDays: course.typicalDays,
          hasMorningSection: course.hasMorningSection,
          hasAfternoonSection: course.hasAfternoonSection,
          hasEveningSection: course.hasEveningSection,
          hasFridayClass: course.hasFridayClass,
          hasOnlineOption: course.hasOnlineOption,
          hasHybridOption: course.hasHybridOption,
          numExams: course.numExams,
          isProjectBased: course.isProjectBased,
          isExamBased: course.isExamBased,
          homeworkIntensity: course.homeworkIntensity,
          isCodingHeavy: course.isCodingHeavy,
          isMathHeavy: course.isMathHeavy,
          examIntensity: course.examIntensity,
          hasGroupProjects: course.hasGroupProjects,
          isMajorRequirement: course.isMajorRequirement,
          isTechElective: course.isTechElective,
          isGenEd: course.isGenEd,
          isLabCredit: course.isLabCredit,
          requirementCategory: course.requirementCategory,
        },
      });
      seededCount++;
      console.log(`  ✓ ${course.code}: ${course.name}`);
    } catch (error) {
      console.error(`  ✗ Failed to seed ${course.code}:`, error);
    }
  }

  console.log(`\n✅ Successfully seeded ${seededCount} courses!`);

  // Summary stats
  const majorReqs = ECE_COURSES.filter(c => c.isMajorRequirement).length;
  const techElectives = ECE_COURSES.filter(c => c.isTechElective).length;
  const labCredits = ECE_COURSES.filter(c => c.isLabCredit).length;
  const onlineCourses = ECE_COURSES.filter(c => c.hasOnlineOption).length;

  console.log(`\n📊 Course Summary:`);
  console.log(`   Major Requirements: ${majorReqs}`);
  console.log(`   Technical Electives: ${techElectives}`);
  console.log(`   Lab Credits: ${labCredits}`);
  console.log(`   Online Available: ${onlineCourses}`);
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
